### ISSUE TITLE
Documentation feedback: /docs/sources/reference/components/prometheus.exporter.mssql.md

### ISSUE THREAD

**Issue by TomClqncy** [grafana/alloy#1109]
The doc says that, in order to create a custom metric, you need to use the query_config parameter to specify a file containing the SQL queries to execute.
The main issue is that prometheus.exporter.mssql can't read the file by path. So you need to use this:

```
local.file "ymlconfiglocation" {
  filename = "./configs/dbcm.yml"
}

prometheus.exporter.mssql "mysqlconnection" {
  connection_string = "myconnectionstring"
  query_config = local.file.ymlconfiglocation.content
}
```

It would be beneficial to have that in the doc.
Thanks

**Comment by hainenber** [comment]
The Alloy doc does mention about using `local.file`'s export as one of examples to pass to `query_config` parameter

<img width="865" alt="image" src="https://github.com/grafana/alloy/assets/41283691/663110e8-bd34-4364-b284-5d9a51cc0d85">

Maybe having an example would be beneficial in this case :D

**Comment by brunogonzalez** [comment]
Hi,
many thank to @TomClqncy because this was far from obvious when using it for the first time. An example would indeed not cost much and help plenty !

**Comment by 6fears7** [comment]
And here's an example if anyone would like to use it:

```alloy
local.file "custom" {
	filename = "./custom-config.yaml"
}

prometheus.exporter.mssql "custom" {
	connection_string = redacted
	query_config      = local.file.custom.content
}
```

```yaml
# custom-config.yaml
collector_name: custom_metrics
metrics:
   - metric_name: sqlserver_waiting_tasks
    help: The host the sql instance is living
    type: gauge
    values: [value]
    query: SELECT COUNT(waiting_task_address) as value FROM sys.dm_os_waiting_tasks
```
