### ISSUE TITLE
Clearing data to develop

### ISSUE THREAD

**Issue by craftzneko** [grafana/alloy#1184]
### What's wrong?

I am trying alloy and loki so using it in a development environment. I have made some config changes and want to have alloy reasses all the existing log files and send them to loki again. My loki config looks like this

```yaml
auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks
```
My alloy config looks like this
```yaml
local.file_match "local_files" {
    path_targets = [{"__path__" = "/test/logs/*.log"}]
    sync_period = "5s"
}

loki.source.file "log_scrape" {
   targets    = local.file_match.local_files.targets
   forward_to = [loki.process.filter_logs.receiver]
   tail_from_end = true
}

loki.process "filter_logs" {
  stage.drop {
       source = ""
       expression  = ".*Connection closed by authenticating user root"
       drop_counter_reason = "noisy"
    }
  forward_to = [loki.process.add_static_label.receiver]
  }

loki.process "add_static_label" {
    forward_to = [loki.write.grafana_loki.receiver]

  stage.static_labels {
      values = {
        logs = "expressapi",
        env = "production",
      }
  }
}

  loki.write "grafana_loki" {
  endpoint {
    url = "http://lokitest.cardiff.gov.uk:3100/loki/api/v1/push"

    // basic_auth {
    //  username = "admin"
    //  password = "admin"
    // }
  }
}
```

I stopped loki service on the server and alloy on the client, cleared the c:\tmp\loki folder on server and C:\ProgramData\GrafanaLabs\Alloy\data on client, rebooted both, restarted loki service and alloy service. So as far as i can see this should now mean its clean ready to be run again. I found no advice in any of the documentation about this

Logs are not ingested and appears as if loki is empty with no labels. Alloy says its healthy and if i add a new log file it has never seen before it seems to ingest it but doesnt process any existing logs. So where is it storing this data so i can clear in between testing!!!

### Steps to reproduce

as above
