### ISSUE TITLE
prometheus.receive_http component cannot receive recording rules 

### ISSUE THREAD

**Issue by Avigdorrr** [grafana/alloy#1288]
### What's wrong?

prometheus.receive_http component cannot receive recording rules.
i have an openshift cluster and Im trying to remote write the metrics to a grafana alloy instance. When i filter to send metrics that are not recording rules like “container_memory_working_set_bytes” the component works fine. But if i add any recording rules like “namespace_workload_pod:kube_pod_owner:relabel”. I get an error that says: “job or instance cannot be found from labels”

### Steps to reproduce

Remote write recording rules metric with a colon to grafana alloy

### System information

OpenShift cluster 4.12

### Software version

Grafana alloy:v1.0.0

**Comment by ahalam** [comment]
FWIW, I added job and instance labels to my Prometheus remote_write rules and it seems to help.

```
remote_write:
- url: [YOUR_REMOTE_WRITE_URL]
  remote_timeout: 30s
  write_relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: ^$|^null$
    target_label: job
    replacement: kube-prometheus
    action: replace
  - source_labels: [instance]
    separator: ;
    regex: ^$|^null$
    target_label: instance
    replacement: recording-rules
    action: replace
  protobuf_message: prometheus.WriteRequest
  follow_redirects: true
  enable_http2: false
  queue_config:
    capacity: 10000
    max_shards: 50
    min_shards: 1
    max_samples_per_send: 2000
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 5s
    sample_age_limit: 10m
  metadata_config:
    send: true
    send_interval: 1m
    max_samples_per_send: 2000
```
