### ISSUE TITLE
[helm] Alloy Helm chart should include the option for setting `--cluster.name`

### ISSUE THREAD

**Issue by petewall** [grafana/alloy#1360]
### Request

In order to differentiate between different Alloy clusters in the same namespace on the same Kubernetes cluster, we should be able to set `--cluster.name` using the Helm chart.

```yaml
alloy:
  clustering:
    enabled: true
    name: "log-gathering-cluster"
```

### Use case

It would make differentiating between alloy instances on the same cluster easier.
