### ISSUE TITLE
Collecting a .json file from Gitlab runner job

### ISSUE THREAD

**Issue by marcanio** [grafana/alloy#1425]
### What's wrong?

I am trying to configure alloy to pick up a .json file created from a gitlab job. So I have labeled my gitlab runner pod so that alloy can pick it up and it does but I need it to pick up the .json file that was created in the job. I found the file that was created on the node and am speccing that path in the relabel. In the Alloy UI I can see that the file_match is looking in the correct directory but it does not have any targets therefore the Loki.source.file does not show any values. 

### Steps to reproduce

Create a gitlab runner job with the label Alloy is looking for. This will forward logs to Loki for that job fine but when you create a .json file in that job it does not forward that file

### System information

Kubernetes 1.29.6

### Software version

Grafana Alloy 1.2.1

### Configuration

```text
alloy:
  configMap:
    content: |-
      logging {
        level = "debug"
        format = "json"
      }

      remote.kubernetes.secret "credentials_loki" {
        namespace = "prometheus-stack"
        name = "loki-basic-creds"
      }

      loki.write "default" {
        endpoint {
          url = "http://loki.tools/loki/api/v1/push"
          headers = {
            "X-Scope-OrgID" = "5",
          }
          basic_auth {
            username = "loki-user"
            password = remote.kubernetes.secret.credentials_loki.data["password"]
          }
          tenant_id = "5"
        }
      }

      discovery.kubernetes "gitlab_runner_pods" {
        role = "pod"

        namespaces {
          names = ["gitlab-runner"]
        }

        selectors {
          role = "pod"
          label = "enable_loki=bsf-dso"
        }

      }

      discovery.relabel "gitlab_runner_pods" {
        targets = discovery.kubernetes.gitlab_runner_pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }
      }

      loki.source.kubernetes "gitlab_runner_pods" {
        targets    = discovery.relabel.gitlab_runner_pods.output
        forward_to = [loki.write.default.receiver]
      }

      discovery.relabel "json_files" {
        targets = discovery.kubernetes.gitlab_runner_pods.targets
        rule {
          source_labels = ["__meta_kubernetes_namespace", "__meta_kubernetes_pod_label_name"]
          target_label  = "job"
          separator     = "/"
        }

        rule {
          source_labels = ["__meta_kubernetes_pod_uid"]
          target_label  = "__path__"
          replacement   = "/var/lib/kubelet/pods/$1/**/*.json"
        }
      }

      local.file_match "json_files" {
        path_targets = discovery.relabel.json_files.output
      }

      loki.source.file "json_files" {
        targets = local.file_match.json_files.targets
        forward_to = [loki.write.default.receiver]
      }
```

**Comment by marcanio** [comment]
To update this.. I have added the volume mount and now see the files I need inside of the alloy pod.. But I can only get alloy to pick up the file when explicitly providing the exact file path in the `replacement` section. I have not been able to get any wildcards to work

**Comment by marcanio** [comment]
If anyone else runs into this I got it working with this config ->
```
controller:
  volumes:
    extra:
      - name: json-files
        hostPath:
          path: /var/lib/kubelet/pods
  nodeSelector:
    karpenter.sh/nodepool: 
  tolerations:
    - key: ""
      effect: "NoSchedule"
  priorityClassName: ''
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/tls-acme: "true"
  hosts:
    - alloy.DOMAIN_NAME
  tls:
    - hosts:
      - alloy.DOMAIN_NAME
      secretName: alloy-tls
alloy:
  mounts:
    extra:
      - name: json-files
        mountPath: /var/lib/kubelet/pods
        readOnly: true
```
