### ISSUE TITLE
add lifecycle on pod_template

### ISSUE THREAD

**Issue by jianpingzhangBill** [grafana/alloy#1673]
### Request

We running alloy in daemonset to collect pod logs. 
We use AWS spot node, it often was  removed. But the alloy pods recycled faster then other pods, it will cause some log didn't send to loki.

Can you help add `lifecycle` and `terminationGracePeriodSeconds` to pod_template?
```
lifecycle:
  preStop:
    exec:
      command: ["sleep", "30"]
```

### Use case

Can you help add `lifecycle` and `terminationGracePeriodSeconds` to pod_template?
```
terminationGracePeriodSeconds: 60
lifecycle:
  preStop:
    exec:
      command: ["sleep", "30"]
```
