### ISSUE TITLE
ServiceMonitor lack custom namespace option

### ISSUE THREAD

**Issue by karlosmunjos** [grafana/alloy#1763]
### Request

ServiceMonitor in all Grafana (didn't checked all) projects helm charts has an option to customise deployment namespace.
This is not the case for Alloy. 

```yaml
{{- $values := (mustMergeOverwrite .Values.alloy (or .Values.agent dict)) -}}
{{- if and .Values.service.enabled .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "alloy.fullname" . }}
  
  namespace: is-missing

  labels:
    {{- include "alloy.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
```

### Use case

I would prefer deploying serviceMonitor resources only to whitelisted namespaces like kube-system and namespace where prometheus is deployed.
