### ISSUE TITLE
/bin/alloy: Operation not permitted

### ISSUE THREAD

**Issue by aleixmorgadas** [grafana/alloy#177]
### What's wrong?

When deploying to [Render](https://render.com/) as a private service, Alloy doesn't start and crashes with an obscure message.

```
root@<host>:~# /bin/alloy          
bash: /bin/alloy: Operation not permitted
```

I debugged the service to try to find more without success:

```
root@<host>:~# strace -f /bin/alloy 
execve("/bin/alloy", ["/bin/alloy"], 0x7ffdec45b6c8 /* 40 vars */) = -1 EPERM (Operation not permitted)
strace: exec: Operation not permitted
+++ exited with 1 +++
```

I also opened a [post](https://community.render.com/t/unable-to-deploy-grafana-alloy/20716/2) at Render.

### Steps to reproduce

Deploy Grafana Alloy to Render.com using the next Dockerfile

```Dockerfile
# syntax = docker/dockerfile:1.2
FROM grafana/alloy:latest
ENTRYPOINT ["/bin/alloy"]
CMD ["run", "--server.http.listen-addr=0.0.0.0:12345", "/etc/alloy/config.alloy"]
```

### System information

Linux 5.15.0-1052-aws #57-Ubuntu SMP Mon Jan 15 15:24:00 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Software version

v1.0.0

**Comment by rfratto** [comment]
Thanks for reporting. This sounds like something specific to Render, since I can't reproduce locally. Can you share more about Render's operating environment that would maybe clue us in to what might be going wrong here? (Such as security settings?)

**Comment by aleixmorgadas** [comment]
I don't find relevant information, but I know that they provide instances on top of AWS. If they reply, I will pass the information here.

Meanwhile, I will try to deploy it from the source code :+1:

**Comment by aleixmorgadas** [comment]
I have successfully deployed Alloy by:

1. Forking the project and deploy a Golang service from source
2. Attaching a Disk

Looks like Alloy (differently than Agent) expects to write to disk. Is there an option to disable it?

https://community.render.com/t/unable-to-deploy-grafana-alloy/20716/3?u=aleixmorgadas

**Comment by aleixmorgadas** [comment]
Which are the directories that Alloy uses to write files into? I think the issue is that it uses more than one directory like the one passed as parameter `--storage.path=/var/lib/alloy/data` but other ones.

**Comment by rfratto** [comment]
> Which are the directories that Alloy uses to write files into? I think the issue is that it uses more than one directory like the one passed as parameter --storage.path=/var/lib/alloy/data but other ones.

`--storage.path` should be the only folder Alloy writes into directly; if it's trying to write to other folders by default that's a bug. (The default value for `--storage.path` is `data-alloy/` and unfortunately on-disk storage can't be disabled right now, but _can_ be set to a tmpfs mount).

**Comment by rwunderer** [comment]
Not sure if it's related, but I had the above error when running Alloy with a `securityContext` dropping all capabilities. I had to add the following capabilities to make it work:

```
      securityContext:
        ...
        capabilities:
          drop:
          - ALL
          add:
          - CHOWN
          - DAC_OVERRIDE
          - FOWNER
          - FSETID
          - KILL
          - SETGID
          - SETUID
          - SETPCAP
          - NET_BIND_SERVICE
          - NET_RAW
          - SYS_CHROOT
          - MKNOD
          - AUDIT_WRITE
          - SETFCAP
          ...
```
