### ISSUE TITLE
Support converting otel config which uses a common receiver across pipelines with different names

### ISSUE THREAD

**Issue by erikbaranowski** [grafana/alloy#1780]
## Problem

There is an existing unit test that demonstrates this limitation [here](https://github.com/grafana/alloy/blob/main/internal/converter/internal/otelcolconvert/testdata/otelcol_errors/duplicate_receivers.yaml): 

Example Config:

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: database:4317

# A receiver may not appear in two different groups.
service:
  pipelines:
    metrics: # Group <empty>
      receivers: [otlp]
      processors: []
      exporters: [otlp]
    traces/2: # Group 2
      receivers: [otlp]
      processors: []
      exporters: [otlp]
```

Output
```
(Critical) the configuration is unsupported because the receiver "otlp" is used across multiple pipelines with distinct names
```

## Research

__NOTE: For the purpose of discussion, I will continue with the "group" terminology as described in the above config ^^^__

We can see that each group is converted independently in the `otelconvert` package [here](https://github.com/grafana/alloy/blob/f9054d30ed46ade7a2f87af688e5860410c3ac31/internal/converter/internal/otelcolconvert/otelcolconvert.go#L258): 

Without the prior [validation](https://github.com/grafana/alloy/blob/f9054d30ed46ade7a2f87af688e5860410c3ac31/internal/converter/internal/otelcolconvert/otelcolconvert.go#L173), this would result in a theoretical pair of receivers using identical ports. Alloy will fail to start up one of the components successfully due to this collision.

```
otelcol.receiver.otlp "default" { ... }

otelcol.receiver.otlp "default_2" { ... } // This uses the same exact ports and cannot start up!!!
```

Further complicating the issue, the lower-level converter code specific to `otelcol.receiver.otlp` [here](https://github.com/grafana/alloy/blob/main/internal/converter/internal/otelcolconvert/converter_otlpreceiver.go) requires that when it builds an `otelcol.receiver.otlp` component it has fully built the component. In other words, we cannot add additional outputs to a component as we loop through future groups and need to know all up front what the complete list of outputs are across all groups. This awareness of other groups may require some more intrusive changes to the `otelconvert` package.
