### ISSUE TITLE
wrong template

### ISSUE THREAD

**Issue by nepia11** [grafana/alloy#1864]
maybe, the template is wrong.
Additional volumes in controller.volumes.extra will result in strange rendering results.

values
```yaml
controller:
  volumes:
    extra:
      - name: cluster-config
        configMap:
          name: cluster-config
      - name: sys
        hostPath:
          path: /sys
      - name: proc
        hostPath:
          path: /proc
```

rendered parts
```yaml
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: dockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            -
              mountPath: /cluster-name
              name: cluster-config
              subPath: CLUSTER_NAME
            -
              mountPath: /sys
              name: sys
            -
              mountPath: /proc
              name: proc
```
