### ISSUE TITLE
Metrics scraped by Grafana Agent sometimes exhibit abnormally large values

### ISSUE THREAD

**Issue by aerfio** [grafana/alloy#188]
### What's wrong?

As in title, metrics scraped by Grafana Agent sometimes have gigantic values. This issue happens to various metrics, coming from various components implemented mostly in Go and Erlang, happening on various k8s clusters. 

At $work we deploy grafana-agent as one of the first steps of k8s cluster creation to scrape metrics, send logs and traces to central monitoring. Recently, we've observed several of our metrics exihibiting bizzare values, like here:
<img width="1941" alt="image" src="https://github.com/grafana/agent/assets/17271979/fbeae809-01b5-42df-83db-decab1e3385a">

Where the "typical" range for this value is more or less [0, 10^6]. We've also seen "gaps" in metrics right after this spike, like shown ^. 

The minimal reproduction setup that's failing looks as follows:
```mermaid
flowchart TD
    A[Pod] -->|scraped by| B[Grafana Agent]
    B --> C[Prometheus]
```

Initial "production" setup where this issue was observed involved 1 more grafana-agent, which acted as grpc server that collected OTLP signals from N clusters, which then sent it to mimir. 

To ensure that the source of problem is in grafana-agent (or our config) I've deployed [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) to affected cluster with following values.yaml:
```yaml
defaultRules:
  create: false
grafana:
  enabled: true
  forceDeployDashboards: false
crds:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
windowsMonitoring:
  enabled: false
alertmanager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
kubeApiServer:
  enabled: false
prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/hostname: redacted # I tired 3 different nodes to be sure
    enableAdminAPI: true
    enableRemoteWriteReceiver: true
    retention: 7d
    scrapeInterval: 30s
    logLevel: warn
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    storageSpec:
      disableMountSubPath: true
      volumeClaimTemplate:
        spec:
          storageClassName: redacted
          resources:
            requests:
              storage: 30Gi
```

I've not observed those issues In grafana from kube-prom-stack. I've also checked those values directly on the pods - they're also fine in the source. This issue IS however visible if I disable kube-prom-stack service monitor scraping and push those metrics using Grafana Agent to the `/api/v1/write` prometheus endpoint. This change is config is visible in provided config.

Also, this issue is not happening only on 1 particular cluster, we've created a dashboard to roughly showcase when it happens for any cluster in our company: 
<img width="2544" alt="image" src="https://github.com/grafana/agent/assets/17271979/83ce1294-1f2a-4636-8658-2ba14a406739">
Other dashboard:
<img width="2292" alt="image" src="https://github.com/grafana/agent/assets/17271979/283718f4-eb2c-45de-86df-6c2d68cbfbfa">

Generally speaking those "gigantic" values are usually near 10^17,  close to max int64 value, which is ~9.223372036854776e+18 (I'm not sure whether it's connected, just pointing it out).

Grafana Agent did not restart at all and there haven't been any logs that were connected to this issue at all. All components are also healthy (this screenshot contains more components than in minimal repro, but when I tested that it was also all green): 
<img width="1383" alt="image" src="https://github.com/grafana/agent/assets/17271979/ad238754-9a9e-4ac4-8800-6dddbf446415">

Provided Grafana Agent config has been heavily inspired by https://github.com/grafana/agent-modules/blob/main/modules/k8s_pods/module.river.

### Steps to reproduce

Maybe using provided config might reproduce this issue.

### System information

`uname -a` on the node: Linux XYZ 5.15.0-101-generic grafana/agent#111-Ubuntu SMP Tue Mar 5 20:16:58 UTzC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Software version

Grafana Agent v0.40.3

### Configuration

```text
logging {
  format = "json"
  level  = "info"
}
prometheus.operator.servicemonitors "services" {
    forward_to = [otelcol.receiver.prometheus.default.receiver]
    clustering {
        enabled = true
    }
    rule {
        target_label = "k8s_cluster_name"
        replacement = "XYZ"
    }
    rule {
        source_labels = [
            "__meta_kubernetes_pod_label_app_kubernetes_io_instance",
            "__meta_kubernetes_pod_label_app_kubernetes_io_name",
        ]
        target_label = "__helm_name__"
        separator    = "-"
        regex        = "(.+-.+)"
    }
    rule {
        // Try to identify a service name to eventually form the job label. We'll
        // prefer the first of the below labels, in descending order.
        source_labels = [
            "__meta_kubernetes_pod_label_k8s_app",
            "__meta_kubernetes_pod_label_app",
            "__meta_kubernetes_pod_label_name",
            "__helm_name__",
            "__meta_kubernetes_pod_controller_name",
            "__meta_kubernetes_pod_name",
        ]
        target_label = "__service__"
        // Our in-memory string will be something like A;B;C;D;E;F, where any of the
        // letters could be replaced with a label value or be empty if the label
        // value did not exist.
        //
        // We want to match for the very first sequence of non-semicolon characters
        // which is either prefaced by zero or more semicolons, and is followed by
        // zero or more semicolons before the rest of the string.
        //
        // This is a very annoying way of being able to do conditionals, and
        // ideally we can use River expressions in the future to make this much
        // less bizarre.
        regex = ";*([^;]+);*.*"
    }
    rule {
        source_labels = ["__meta_kubernetes_pod_node_name"]
        target_label  = "__host__"
    }
    rule {
        source_labels = [
            "__meta_kubernetes_namespace",
            "__service__",
        ]
        target_label = "job"
        separator    = "/"
    }
    rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
    }
    rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
    }
    rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label  = "container"
    }
    rule {
        source_labels = ["__meta_kubernetes_pod_label_app"]
        target_label  = "app"
    }
    rule {
        source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
        target_label  = "name"
    }
}
module.git "k8s_api" {
  repository = "https://github.com/grafana/agent-modules.git"
  revision   = "65de0463c41f9027608132ec11c2f7ed411eb107"
  path       = "modules/k8s_api/module.river"
  arguments {
    forward_metrics_to = [otelcol.receiver.prometheus.default.receiver]
  }
}
otelcol.receiver.prometheus "default" {
    output {
        metrics = [otelcol.processor.k8sattributes.default.input]
    }
}
otelcol.processor.k8sattributes "default" {
    extract {
        label {
            from      = "pod"
            key_regex = "(.*)/(.*)"
            tag_name  = "$1.$2"
        }
        metadata = [
            "k8s.pod.name",
            "k8s.pod.uid",
            "k8s.deployment.name",
            "k8s.node.name",
            "k8s.namespace.name",
            "k8s.pod.start_time",
            "k8s.replicaset.name",
            "k8s.replicaset.uid",
            "k8s.daemonset.name",
            "k8s.daemonset.uid",
            "k8s.job.name",
            "k8s.job.uid",
            "k8s.cronjob.name",
            "k8s.statefulset.name",
            "k8s.statefulset.uid",
            "k8s.container.name",
            "container.image.name",
            "container.image.tag",
            "container.id",
        ]
    }
    output {
        traces  = [otelcol.processor.transform.add_cluster_name.input]
        logs    = [otelcol.processor.transform.add_cluster_name.input]
        metrics = [otelcol.processor.transform.add_cluster_name.input]
    }
}

otelcol.processor.transform "add_cluster_name" {
  error_mode = "ignore"
  metric_statements {
      context = "datapoint"
      statements = [
        "set(attributes[\"k8s.cluster.name\"], \"XYZ\")",
      ]
  }
  trace_statements {
      context = "resource"
      statements = [
        "set(attributes[\"k8s.cluster.name\"], \"XYZ\")",
      ]
  }
  log_statements {
      context = "resource"
      statements = [
        "set(attributes[\"k8s.cluster.name\"], \"XYZ\")",
      ]
  }
  output {
      metrics = [otelcol.processor.batch.default.input]
      traces  = [otelcol.processor.batch.default.input]
      logs    = [otelcol.processor.batch.default.input]
  }
}
otelcol.processor.batch "default" {
    timeout = "5s"
    send_batch_size = 4096
    send_batch_max_size = 8192
    output {
        metrics = [otelcol.exporter.otlp.default.input,otelcol.exporter.prometheus.prom.input]
        logs    = [otelcol.exporter.otlp.default.input]
        traces  = [otelcol.exporter.otlp.default.input]
    }
}
otelcol.exporter.otlp "default" {
    client {
        endpoint = "**redacted**"
        auth = otelcol.auth.basic.default.handler
    }
}
otelcol.exporter.prometheus "prom" {
    forward_to = [prometheus.remote_write.prom.receiver]
}
prometheus.remote_write "prom" {
    endpoint {
        url = "http://kps-prometheus.monitoring:9090/api/v1/write"
    }
}
otelcol.auth.basic "default" {
    username = env("CTA_BASIC_AUTH_USERNAME")
    password = env("CTA_BASIC_AUTH_PASSWORD")
}
```
