### ISSUE TITLE
Alloy running in docker does not see network interface metrics from the host

### ISSUE THREAD

**Issue by maitmandel** [grafana/alloy#1933]
### What's wrong?

Alloy running in docker does not see counters for all interfaces. It does see that the interfaces exist, but most most counters are empty:

![Image](https://github.com/user-attachments/assets/e18d3122-f2bd-4f97-a7ef-ce16281401a5)

### Steps to reproduce

Run Alloy in docker container, mounting the devices etc from host

### System information

Ubuntu 24.04 LTS

### Software version

Grafana Alloy v1.4.1

### Configuration

compose.yaml:
services:
  alloy :
    image: grafana/alloy:v1.4.1
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /var/log:/host-var-log
      - /proc:/host-proc
      - /sys:/host-sys
      - /:/host-root
      - /run/udev/data:/host-udev
    env_file:
      - .env
    cap_add:
      - SYS_PTRACE
    privileged: true
    command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

config.alloy:
prometheus.exporter.unix "default" {
 procfs_path = "/host-proc/"
 sysfs_path = "/host-sys/"
 rootfs_path = "/host-root/"
 udev_data_path = "/host-udev/"
}

**Comment by db-wally007** [comment]
> ### What's wrong?
> Alloy running in docker does not see counters for all interfaces. It does see that the interfaces exist, but most counters are empty:
> 
> ![Image](https://github.com/user-attachments/assets/e18d3122-f2bd-4f97-a7ef-ce16281401a5)
> 
> Notice how _node_network_info_ also lists devices like _enx0_ etc but _node_network_receive_bytes_total_ only has metrics from _eth0_ and _lo_
> 
> ### Steps to reproduce
> Run Alloy in docker container, mounting the devices etc from host
> 
> ### System information
> Ubuntu 24.04 LTS
> 
> ### Software version
> Grafana Alloy v1.4.1
> 
> ### Configuration
> compose.yaml:
> 
> ```
> services:
>   alloy :
>     image: grafana/alloy:v1.4.1
>     volumes:
>       - ./config.alloy:/etc/alloy/config.alloy
>       - /var/log:/host-var-log
>       - /proc:/host-proc
>       - /sys:/host-sys
>       - /:/host-root
>       - /run/udev/data:/host-udev
>     env_file:
>       - .env
>     cap_add:
>       - SYS_PTRACE
>     privileged: true
>     command: run --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
> ```
> 
> config.alloy:
> 
> ```
> ...
> prometheus.exporter.unix "default" {
>  procfs_path = "/host-proc/"
>  sysfs_path = "/host-sys/"
>  rootfs_path = "/host-root/"
>  udev_data_path = "/host-udev/"
> }
> ...
> ```
> 
> ### Logs
> _No response_

Were you able to find a fix for this ?

I'm experiencing the same using FEDORA 41 and podman. 

1, 
I've mounted hosts system directories inside the container:

Node exporter integration config:
```
      procfs_path        = "/hostfs/proc"
      sysfs_path         = "/hostfs/sys"
      rootfs_path        = "/hostfs"
      udev_data_path     = "/hostfs/run/udev/data"
```

Kube manifest volumes:
```yaml
  volumes:
  - name: sys-volume
    hostPath:
      path: /sys
      type: Directory
  - name: proc-volume
    hostPath:
      path: /proc
      type: Directory
  - name: udev-volume
    hostPath:
      path: /run/udev/data
      type: Directory
  - name: rootfs-volume
    hostPath:
      path: /
      type: Directory
```

Kube manifest container:
```yaml
   volumeMounts:
    - name: sys-volume
      mountPath: /hostfs/sys
      readOnly: true
    - name: proc-volume
      mountPath: /hostfs/proc
      readOnly: true
    - name: udev-volume
      mountPath: /hostfs/run/udev/data
      readOnly: true
    - name: rootfs-volume
      mountPath: /hostfs
      readOnly: true
```

For example `node_network_speed_bytes` shows host interface statistics.

`node_network_speed_bytes{device="enp4s0", instance="server", job="node_exporter-20s"}` 

But `node_network_receive_frame_total` shows container interface statistics

`node_network_receive_frame_total{device="eth0", instance="server", job="node_exporter-20s"}`


This seems like a bug to me, rather than wrong configuration (looks like some metrics lookups are hard coded)
