### ISSUE TITLE
Docs feedback: Helm chart alloy.extraPorts.hostPort should be port instead

### ISSUE THREAD

**Issue by jkruke** [grafana/alloy#1997]
### URL

https://artifacthub.io/packages/helm/grafana/alloy#alloy-extraports

### Feedback

If I configure `alloy.extraPorts` according to the documentation as follows:
```
alloy:
  extraPorts:
    - targetPort: 4317
      hostPort: 4317
      name: otlp-grpc
```
I get this error from kubernetes after helm upgrade:
```
Error: UPGRADE FAILED: cannot patch "alloy" with kind Service: Service "alloy" is invalid: spec.ports[1].port: Invalid value: 0: must be between 1 and 65535, inclusive
```
This is because the generated manifest looks like this:
```
...
    ports:
      - name: http-metrics
         port: 12345
         targetPort: 12345
         protocol: "TCP"
      - name: otlp-grpc
        port: 
        targetPort: 4317
        protocol: TCP
.... 
```
So I changed configuration to the following:
```
alloy:
  extraPorts:
    - targetPort: 4317
      port: 4317
      name: otlp-grpc
```
...and it worked well!

This should be reflected to the documentation.
