### ISSUE TITLE
discovery.dockerswarm "service" role Unable to refresh target groups

### ISSUE THREAD

**Issue by tomdaley92** [grafana/alloy#2014]
### What's wrong?

The `discovery.dockerswarm` fails to refresh targets for just the "service" role with minimal configuration. The same `discovery.dockerswarm` component (as shown in config file below) is able to export targets successfully for the roles `tasks` and `nodes` on the same host/docker-daemon.

I have several stack/services running on this single node docker swarm manager. The error from the logs makes me think there is some variable "default" is missing when calling the downstream `prometheus swarm service discovery` under the hood.

### Steps to reproduce

1. Initialize a single node docker swarm manager on Ubuntu 20.04 LTS
2. Write configuration file to `/home/automation/applications/alloy/dev/config/config.alloy`
3. Deploy Alloy container as a swarm service using this **docker-compose.yaml** file with the `docker stack deploy` command. Since alloy is a service we should be able to get a target for itself, although you may want to deploy other random stacks/services on the node to ensure other service targets are available.

```yaml
# docker-compose.yaml
version: '3.8'
services:

  daemon:
    image: grafana/alloy:v1.4.3
    hostname: '< redacted >'
    volumes:
      - '/etc/localtime:/etc/localtime'
      - '/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt'
      - '/home/automation/applications/alloy/dev/data/:/var/lib/alloy/data'
      - '/home/automation/applications/alloy/dev/config/config.alloy:/etc/alloy/config.alloy'
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs/:ro
      - /sys:/hostfs/sys:ro
      - /proc:/hostfs/proc:ro
      - /var/log:/hostfs/var/log:ro
      - /run/udev/data:/hostfs/run/udev/data:ro
    ports:
      - '12345:12345'
    command:
      - run
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    deploy:
      mode: global
      restart_policy:
        condition: any
    networks:
      - hostnet

networks:
  hostnet:
    name: host
    external: yes
```

### System information

Ubuntu 20.04.6 LTS, Docker Engine 25.0.4

### Software version

grafana/alloy:v1.4.3

### Configuration

discovery.dockerswarm "node" { // WORKING
  host             = "unix:///var/run/docker.sock"
  refresh_interval = "60s"
  role             = "nodes"
}

discovery.dockerswarm "service" { // NOT WORKING
  host             = "unix:///var/run/docker.sock"
  refresh_interval = "15s"
  role             = "services"
}

discovery.dockerswarm "task" { // WORKING
  host             = "unix:///var/run/docker.sock"
  refresh_interval = "15s"
  role             = "tasks"
}

### Logs

ts=2024-10-31T20:34:40.886224195Z level=error msg="Unable to refresh target groups" component_path=/ component_id=discovery.dockerswarm.service err="error while parsing address : invalid CIDR address: "
