### ISSUE TITLE
wrong ingress.faroPort for ingress values in alloy helm chart

### ISSUE THREAD

**Issue by mkhodave** [grafana/alloy#2128]
### What's wrong?

I can see wrong _faroPort: 12347_ which is not matching with _alloy.listenPort_ , due to this even ingress enabled for alloy the ingress host can not accessible & loads default nginx 503 error page.

I am seeing these values even latest helm chart version 0.10.0 for alloy

### Steps to reproduce

ingress:
  enabled: true

deploy alloy with ingress enabled as shown above

### Software version

Grafana Alloy helm chart version 0.10.0

### Configuration

```text

```

### Logs

```text

```

**Comment by shihvicky** [comment]
@mkhodave I met the same problem, but finally I solved this problem. 
As you mentioned, yes, you are correct, the port number is not 12347. The correct port number can be got from the result of kubectl get svc

```
[devops@node1 alloy]$ kubectl get svc
NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
alloy                           ClusterIP   10.99.250.209    <none>        12345/TCP           77m
alloy-cluster                   ClusterIP   None             <none>        12345/TCP           77m
```

and here is the settings of ingress in my values.yaml

```
ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  faroPort: 12345
  pathType: Prefix
  hosts:
    - alloy.example.com
 ```

after installation, I can visit it by url: http://alloy.example.com:32080/

**Comment by mkhodave** [comment]
Thanks @shihvicky for confirming & I also did same trick then it started working.
This should be fixed in upstream itself.

**Comment by ChinthapalliNikhithaChandana** [comment]
Hi, 

I'm trying to expose faro port using ingress but seeing 404 error. Can you advice?

```yaml
  extraPorts:
    - name: faro
      port: 12347
      targetPort: 12347
      protocol: "TCP"
```
```yaml
ingress:
  enabled: true
  ingressClassName: traefik
  annotaions:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels: {}
  path: /
  faroPort: 12345
  pathType: Prefix
  hosts:
    - alloy.righive.local
  extraPaths:
     - path: /faro
       pathType: Prefix
       backend:
         service:
           name: alloy
           port:
             number: 12347
```
