### ISSUE TITLE
Docs feedback: How to use prometheus.operator.probes

### ISSUE THREAD

**Issue by enneitex** [grafana/alloy#2333]
### URL

https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.operator.probes/#example

### Feedback

Hi,

I'm trying to add the `prometheus.operator.probes` component on my alloy instance but I don't get what my `Probe` should look like.
As I understand, alloy acts as the blackbox exporter so I don't need to deploy it in addition to alloy. (prometheus.exporter.blackbox i working well)

something like this should work or is `spec.prober.url` required ? If so, is it `localhost:12345` ?

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-crd
spec:
  interval: 10s
  module: http_2xx
  targets:
    staticConfig:
      static:
        - https://grafana.com

```

When adding `url: localhost:12345` I get en error: `level=debug msg="Append failed" component_path=/ component_id=prometheus.operator.probes.default scrape_pool=probe/kube-monitoring/probe-crd target="http://localhost:12345/probe?module=http_2xx&target=https%3A%2F%2Fgrafana.com" err="expected a valid start token, got \"<\" (\"INVALID\") while parsing: \"<\""` because this is the UI port I guess

Is it possible to share a working example with a Probe ?

Does an extra Port need to be exposed in alloy container ? Or a dedicated blackbox-exporter pod is required ?

**Comment by alex-berger** [comment]
Same struggle here, example or link to docs highly appreciated.

**Comment by zmeiresearch** [comment]
Just went through the pain of setting that up myself. After almost a full day of reading docs, looking for hints, open bugs, etc, I got it working - with a caveat. The documentation is mostly correct, but there are two important pieces missing.
- Apart from `prometheus.operator.probes`, `prometheus.exporter.blackbox` also needs to be enabled. The alternative is to run blackbox exporter separately but hey, we already have it embedded in Alloy.
- Prober URL/path need to point to the Alloy blackbox exporter component internal API - which works, but as it's not officially documented, may break at some point in the future.

Reference config, assuming Alloy deployed in `monitoring` namespace, exposing its interface/API at `alloy.monitoring.svc.cluster.local:12345`

```
// config.alloy
prometheus.exporter.blackbox "blackbox_exporter" {
  config = "{ modules: { http_2xx: { prober: http, timeout: 5s } } }"  // config is required
}

prometheus.operator.probes "blackbox_exporter_probe" {
  namespaces = ["testns" ]
  forward_to = [ XXX ]
}
```
```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-exporter-core
  namespace: testns
spec:
  jobName: blackbox
  interval: 30s
  module: http_2xx
  prober:
    url: alloy.monitoring.svc.cluster.local:12345
    path: /api/v0/component/prometheus.exporter.blackbox.blackbox_exporter/probe
  targets:
    staticConfig:
      static:
        - testsvc.testns.svc.cluster.local:80
```

To get it working, I got hints from https://github.com/grafana/agent/issues/5936#issuecomment-1862381370 and also https://github.com/grafana/alloy/issues/2596
