### ISSUE TITLE
Helm: Ingress for Alloy UI is exposing only Faro UI port as default

### ISSUE THREAD

**Issue by sergeiwaigant** [grafana/alloy#2346]
### What's wrong?

I was trying to expose the embedded Alloy UI with the Helm Chart and was confused, that the default when enabling the ingress is a rule for the root path to port 12347, which is the default port for Faro.

From my perspective, the default should be routing to Alloy directly and something like `ingress.faro.enabled: true` that will add another paths into the rule to direct a subpath to Faro. Setting this to true should also add all required configurations to Grafana Alloy to enable the Faro UI itself.

Let me know your thoughts, I could implement this, but it would be a breaking change for the Helm Chart I guess.

### Steps to reproduce

Deploy Grafana Alloy with the Helm Chart, set `ingress.enabled: true` and check for the created ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: alloy.kubernetes.corporate.domain
    external-dns.alpha.kubernetes.io/record-type: CNAME
    external-dns.alpha.kubernetes.io/target: kubernetes.corporate.domain
    meta.helm.sh/release-name: alloy
    meta.helm.sh/release-namespace: loki
  labels:
    app.kubernetes.io/component: networking
    app.kubernetes.io/instance: alloy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/version: v1.5.1
    helm.sh/chart: alloy-0.10.1
  name: alloy
  namespace: loki
spec:
  ingressClassName: traefik
  rules:
  - host: alloy.kubernetes.corporate.domain
    http:
      paths:
      - backend:
          service:
            name: alloy
            port:
              number: 12347
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - alloy.kubernetes.corporate.domain
    secretName: alloy-ingress-tls
```

### System information

Helm Chart 0.10.1, Kubernetes v1.31.4

### Software version

Grafana Alloy v1.5.1

### Configuration

```text

```

### Logs

```text

```
