### ISSUE TITLE
Unexpected staleness behavior with influx receiver

### ISSUE THREAD

**Issue by llamafilm** [grafana/alloy#2537]
### What's wrong?

Using Alloy to receive metrics from Telegraf influx line protocol and write to Prometheus.  When a label changes in the source, it should immediately create a new time series and the previous series should stop.  Instead, Alloy continues writing both series for 5 minutes.  This causes a lot of weird displays in Grafana.  One example is the state timeline below.

I believe this is related to "staleness" — a concept which doesn't exist in influx.  So I believe Alloy should make the necessary adjustments/assumptions to avoid this issue.  This same issue is also present when writing from Telegraf to Grafana Cloud's influx2cortex proxy.

An easy way to reproduce is by running Node Exporter, Telegraf, and Alloy.  Telegraf scrapes the Node Exporter and sends influx line protocol to Alloy.  Alloy writes to Prometheus in Grafana Cloud.

After running node_exporter-1.8.1 for a few minutes, kill it and run node_exporter-1.8.2 instead.

![Image](https://github.com/user-attachments/assets/923e4be1-c414-4bf6-8216-d17ed243b448)

![Image](https://github.com/user-attachments/assets/f15f12ef-1ca5-4c4c-8f70-724bcbfd26e4)

### Steps to reproduce

Here is a minimal config for Alloy and Telegraf.  Open 3 terminals and run these 3 commands:
```sh
node_exporter-1.8.1
# node_exporter-1.8.2
telegraf --config telegraf.conf
alloy run config.alloy
```

Alloy config:
```
otelcol.receiver.influxdb "telegraf" {
    endpoint = "localhost:8086"
    output {
        metrics = [otelcol.exporter.prometheus.influx_output.input]
    }
}

otelcol.exporter.prometheus "influx_output" {
    forward_to = [prometheus.remote_write.grafanacloud.receiver]
}

prometheus.remote_write "grafanacloud" {
    endpoint {
        url = "https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push"
        basic_auth {
            username = ""
            password = ""
        }
    }
}
```

Telegraf config:
```toml
[agent]
  interval = "10s"
  round_interval = false
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"

[[inputs.prometheus]]
  urls = ["http://127.0.0.1:9100/metrics"]
  metric_version = 2
  fieldinclude = ["node_exporter_build_info"]
  taginclude = ["version", "host"]

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  skip_database_creation = true
```

### System information

MacOS Sequoia

### Software version

Grafana Alloy v1.6.1

### Configuration

```text

```

### Logs

```text

```
