### ISSUE TITLE
The path of ProberSpec is an empty string by default

### ISSUE THREAD

**Issue by keisuk-t-iij** [grafana/alloy#2596]
### What's wrong?

The path of ProberSpec is defined as /probe by default, but 'prometheus.operator.probes' treats it as an empty string by default.

https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api-reference/api.md#proberspec

### Steps to reproduce

If the path of ProberSpec is omitted, the URL of prober is http://blackbox-exporter:9115 instead of http://blackbox-exporter:9115/probe.

```
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: example
spec:
  module: http_2xx
  prober:
    url: blackbox-exporter:9115
  targets:
    staticConfig:
      static:
      - https://www.example.com
```

### System information

Linux 9.4 x86_64

### Software version

Grafana Alloy v1.6

### Configuration

```text
prometheus.operator.probes "default" {
  forward_to = [prometheus.remote_write.default.receiver]
}
prometheus.remote_write "default" {
  endpoint {
    url = "https://mimir.example.com/api/v1/push"
  }
}
```

### Logs

```text

```
