### ISSUE TITLE
Offer Multiple Docker Images Based on Usage/Needs

### ISSUE THREAD

**Issue by ghost** [grafana/alloy#2726]
First, I’d like to commend the Alloy team for the excellent work on the project. The transition from Promtail to Alloy in one of my open-source projects has been seamless, and the overall experience has been outstanding.

During the migration, I encountered a challenge when setting up health checks for the Alloy container. The official Alloy base image currently lacks networking tools such as `nc` (Netcat), `wget`, or `curl`, which are essential for reliable network-based health checks.

**Request:**
Could you consider **offering multiple Docker images**, one full-featured and another more streamlined? This approach would allow users to manage base image size and vulnerability scanning, as is typical in CI/CD pipelines.

For example, a health check using `wget` could be configured as follows:

```yaml
  alloy:
    image: 'grafana/alloy:v1.6.1'
    container_name: 'alloy'
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ../logs/application.log:/var/log/application.log
    networks:
      - observability-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:12345/metrics" ]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
    depends_on:
      loki:
        condition: service_healthy
```

Currently, without these utilities, users need to extend the Alloy image with custom Dockerfiles, adding unnecessary complexity and overhead.

### Use case

**Offering multiple images** would allow networking tools like `nc`, `wget`, or `curl` to be included in the base image, simplifying container health check configurations. Users would no longer need to extend the image with custom Dockerfiles. Providing these utilities natively would improve usability and align with best practices for containerized application monitoring.

**Comment by ranzyblessings** [comment]
Should the inclusion of `nc`, `wget`, or`curl` align with the team's roadmap and strategic direction for Alloy, I would be glad to contribute and submit a pull request.

**Comment by mattdurham** [comment]
Ideally I would like to limit and reduce the scope of the docker file, to me this would widen it in a way that opens us to more CVEs and maintenance. We have long been trying to find a way to get to more of smaller base image but journalctl support has stopped that.

**Comment by ranzyblessings** [comment]
That makes sense. I understand your concerns about expanding the Docker file and the potential security risks. Given this, would making tools like `wget` or `curl` optional via build-time arguments or environment variables not align with the team's direction? This approach would shift the responsibility of managing base image size and vulnerability scanning to users, as is typical in CI/CD pipelines.

Example:

```dockerfile
# Set build-time argument to conditionally install optional packages
ARG INSTALL_OPTIONAL_PACKAGES=false

# Conditionally install wget based on the build-time argument
RUN if [ "$INSTALL_OPTIONAL_PACKAGES" = "true" ]; then \
    apt-get update && apt-get install -y wget; \
    fi

# Set the environment variable (optional, can be used at runtime)
ENV INSTALL_OPTIONAL_PACKAGES=${INSTALL_OPTIONAL_PACKAGES}
```

**Comment by mattdurham** [comment]
We have thought about multiple docker images, maybe one more full featured and one more streamlined. This would have to become proposal but it is something that reasonably is on our roadmap.

**Comment by ranzyblessings** [comment]
Perfect, sounds great! Would be happy to contribute if the issue would be great for newcomers. Thanks for the feedback!

**Comment by mattdurham** [comment]
Do you mind editing your original comment and title to say offer multiple docker images based on usage/needs and then use the healthcheck example for a reason. That way someone doesnt have to read all the comments to figure out whats going on.

**Comment by ranzyblessings** [comment]
> Do you mind editing your original comment and title to say offer multiple docker images based on usage/needs and then use the healthcheck example for a reason. That way someone doesnt have to read all the comments to figure out whats going on.

Hello, @mattdurham,

I’ve made the suggested changes. Please let me know if everything looks good or if any further adjustments are needed.

**Comment by mattdurham** [comment]
Looks good thank you!

**Comment by sjparkinson** [comment]
This is helpful when running on AWS ECS which makes use of the Docker health check configuration.

In the ADOT AWS collector distribution it was solved by adding a `./healthcheck` command, I guess to avoid including and maintaining `wget` etc.

* https://github.com/aws-observability/aws-otel-collector/pull/1285

**Comment by ranzyblessings** [comment]
Ah, cool! By using a custom health check script instead of relying on external tools like `wget` or `curl`, you reduce the image size and minimize security risks. The Go script is more comprehensive because it checks the HTTP status, ensuring the service is **functioning properly**, not just that a port is open. It’s also flexible (easily change the port or path) and includes port validation, making the health check more robust. This provides a **secure**, **self-contained** solution without additional dependencies.

You can implement this Go program in your Docker container's health check as follows:

```yaml
services:
  alloy:
    image: 'grafana/alloy:v1.6.1'
    container_name: 'alloy'
    healthcheck:
      test: ["CMD", "./healthcheck", "-port", "12345"]  # The port can be omitted and will default to the default port.
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 5s
```

**Important Notice:**

While this solution specifically addresses health checks, **offering multiple Docker images**, such as a minimal version and a more feature-rich version, could still be a valid approach. For instance:

- **Smaller base images** with fewer dependencies reduce the attack surface and enhance security.
- **Larger images with additional tools** (like `curl`, `wget`, or `nc`) might be preferred for users needing a more versatile container with added functionality to simplify debugging or customization. _For example, if the container is having trouble connecting to an external service, tools like curl can help check HTTP connectivity, while `nc` can verify if the required ports are open from within the container._

Since I don’t work at Grafana, we’ll need to wait for @mattdurham  or the team to determine if this fits with their roadmap or if there are other considerations we haven’t anticipated. The solution definitely has great potential @sjparkinson  .
