### ISSUE TITLE
Multi tenant aware grafana agent

### ISSUE THREAD

**Issue by martinjaegerdk** [grafana/alloy#276]
### Request

As far as i can tell, the agents support for multi tenancy is limited to static configuration.
Either through adding a custom `HTTP` header for remote write configurations, or setting `tenant_id` attribute where that is supported.

I have a few use cases, where i would like for the grafana-agent to support dynamic multi tenancy. E.g. setting `tenant_id`/`HTTP Header` based on a label value.

### Use case

Having a common agent that can support scraping data for multiple tenants.

**Comment by romanfurst** [comment]
HI @martinjaegerdk , I haven't tried it myself yet, but it seems like setting label `__tenant_id__` could do the job. Or am I mistaken?

[look here](https://github.com/grafana/alloy/blob/main/internal/component/common/loki/client/client.go#L460)

**Comment by martinjaegerdk** [comment]
@romanfurst Nice find. It certainly looks that way 💪 
I will test this out when i have a use case.
The last time i set it up using a separate agent, which is working fine obviously, so not gonna touch that.

**Comment by TheoBrigitte** [comment]
Using a combination of `loki.relabel` and `loki.source.podlogs` components it is possible to set the tenant id based on a given label from the pod or its namespace.

In the following example the tenant id is taken from the pod label `foo`.

Here is the config and the PodLog resource I used

* Alloy config
```rego
loki.source.podlogs "default" {
  forward_to = [loki.relabel.default.receiver]
}

loki.relabel "default" {
  forward_to = [loki.write.default.receiver]

  rule {
    action = "replace"
    source_labels = ["foo"]
    target_label  = "__tenant_id__"
    replacement = "$1"
    regex = "(.*)"
  }

  rule {
    action = "labeldrop"
    regex = "^foo$"
  }
}

loki.write "default" {
  endpoint {
    url = "https://loki.svc/loki/api/v1/push"
  }
}
```
* PodLog (note: this will select all pods from all namespaces, change the selectors to fit your need)
```yaml
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: pod-tenant-id-from-label
spec:
  selector: {}
  namespaceSelector: {}
  relabelings:
  - action: replace
    sourceLabels: ["__meta_kubernetes_pod_label_foo"]
    targetLabel: "foo"
    replacement: "$1"
    regex: "(.*)"
```

It is also possible to set the tenant id using the `loki.process` component which has a tenant stage which allow for exactly this; setting the tenant id, but from there only log entry content are accessible. 
More info at https://grafana.com/docs/alloy/latest/reference/components/loki/loki.process/#stagetenant-block
