### ISSUE TITLE
Documentation feedback: /docs/sources/reference/components/prometheus/prometheus.exporter.cadvisor.md

### ISSUE THREAD

**Issue by aleexharris** [grafana/alloy#2875]
The cAdvisor exporter doesn't seem to capture the metrics for other containers on the same Docker Compose network as the Grafana Alloy container. The issue is fixed when running cAdvisor as a standalone container.

Example `config.alloy` below

```sh
prometheus.exporter.unix "osx" {}

prometheus.exporter.cadvisor "cadvisor_exporter" {}

prometheus.exporter.redis "redis_exporter" {
    redis_addr = "redis://redis:6379"
}

prometheus.scrape "prometheus_scraper" {
  targets    = concat(
    prometheus.exporter.unix.osx.targets,
    prometheus.exporter.cadvisor.cadvisor_exporter.targets,
    prometheus.exporter.redis.redis_exporter.targets,
  )
  forward_to = [prometheus.remote_write.cloud_hosted_prometheus.receiver]
}

prometheus.remote_write "cloud_hosted_prometheus" {
   endpoint {
      name = "hosted-prometheus"
      url  = sys.env("PROMETHEUS_URL")
  
      basic_auth {
        username = sys.env("PROMETHEUS_USERNAME")
        password = sys.env("GRAFANA_CLOUD_API_KEY")
      }
   }
}
```

Example `compose.yml` below

```yml
  grafana-alloy:
    container_name: grafana-alloy
    image: grafana/alloy:latest
    environment:
      - LOKI_URL=${LOKI_URL}
      - LOKI_USERNAME=${LOKI_USERNAME}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - PROMETHEUS_USERNAME=${PROMETHEUS_USERNAME}
      - GRAFANA_CLOUD_API_KEY=${GRAFANA_CLOUD_API_KEY}
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - logs:/tmp/app/logs
    ports:
      - "12345:12345"
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - project-network
```
