### ISSUE TITLE
prometheus.exporter.postgres export cpu usage

### ISSUE THREAD

**Issue by RulerChen** [grafana/alloy#2881]
I am currently working on building a PostgreSQL monitoring dashboard and using Alloy's `prometheus.exporter.postgres` to export metrics instead of `postgres-exporter`.

However, I noticed that `prometheus.exporter.postgres` does not export `process_cpu_seconds_total` and `process_resident_memory_bytes`, while `postgres-exporter` does include these metrics.

I would like to confirm whether this is due to a misconfiguration in my settings or if Alloy's exporter does not support these process-level metrics by design. Additionally, is there an alternative way to calculate CPU and memory usage of PostgreSQL through Alloy?

[My target dashboard](https://grafana.com/grafana/dashboards/9628-postgresql-database/)

`config.alloy` :

```
prometheus.exporter.postgres "default" {
    data_source_names = ["postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"]
    enabled_collectors = [
        "database",                   
        "database_wraparound",        
        "locks",                      
        "long_running_transactions",  
        "postmaster",                
        "process_idle",               
        "replication",               
        "replication_slot",           
        "stat_activity_autovacuum",   
        "stat_bgwriter",              
        "stat_database",              
        "stat_statements",            
        "stat_user_tables",          
        "stat_wal_receiver",          
        "statio_user_indexes",        
        "statio_user_tables",         
        "wal",                             
    ]    
}

prometheus.scrape "postgres" {
    targets = prometheus.exporter.postgres.default.targets

    forward_to = [prometheus.remote_write.mimir.receiver]

    job_name = "postgres"
}


prometheus.remote_write "mimir" {
    endpoint {
        url = "http://mimir:9009/api/v1/push"

        basic_auth {
            username = ""
            password = ""
        }
    }
}
```

`docker-compse.yaml`

```yaml
services:
  // ...other service
  alloy:
    container_name: alloy
    image: grafana/alloy:v1.6.1
    restart: always
    command: ['run', '--server.http.listen-addr=0.0.0.0:12345', '/etc/alloy/config.alloy']
    healthcheck:
      test:
        [
          'CMD',
          '/bin/bash',
          '-c',
          "echo -e 'GET /-/ready HTTP/1.1\\nHost: localhost\\nConnection: close\\n\\n' > /dev/tcp/localhost/12345"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - ./config/alloy/config.alloy:/etc/alloy/config.alloy
    ports:
      - '12345:12345'
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  postgres:
    container_name: postgres
    image: postgres:16.8
    restart: always
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=pg_stat_statements',
        '-c',
        'pg_stat_statements.track=all'
      ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
```
