### ISSUE TITLE
mimir.rules/`PrometheusRule` should support injecting selector labels

### ISSUE THREAD

**Issue by james-callahan** [grafana/alloy#291]
### Request

The ability to inject a label selector into rules created/managed with the `mimir.rules` component.
e.g. if I have the mimir.rules config of (the newly requested field is something like `inject_labels`):
```hcl
mimir.rules.kubernetes "default" {
  address = env("MIMIR_RULER_URL")
  basic_auth {
    username = env("MIMIR_USERNAME")
    password = env("MIMIR_PASSWORD")
  }
  mimir_namespace_prefix = env("MIMIR_NAMESPACE_PREFIX")

  inject_labels = { cluster = "mycluster" }
}
```

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-example-alerts
spec:
  groups:
  - name: ./example-alert.rules
    rules:
    - alert: ExampleAlert
      expr: my_metric{foo="bar"}
```
would result in a rule loaded of 
```promql
my_metric{cluster="mycluster",foo="bar"}
```

### Use case

This is used to complement `external_labels` added with a `prometheus.remote_write` component.

Without it, the created rules can easily run against a differently namespaced set of metric data.
