### ISSUE TITLE
Digital Ocean SD relabeling doesn't wprk

### ISSUE THREAD

**Issue by rmalenko** [grafana/alloy#2927]
### What's wrong?

Digital ocean droplets have two IP public and private. All node-exporters are listening on private IP. Hoverer, parts of droplets, has only public IP.

### Steps to reproduce

If a private IP is available, Prometheus tries to scrape it; in other cases, it uses a public IP. 

Now I started to use Alloy, and these rules don't work. Alloy always uses public IP for scraping.

Used to Prometheus, I had this relabeling rule, which works well:

```yml
# Prioritize private IPs
- source_labels: [__meta_digitalocean_private_ipv4]
  target_label: __address__
  replacement: "${1}:9100"
  action: replace
# Fallback to public IP only if private IP is missing
- source_labels:
    [__meta_digitalocean_private_ipv4, __meta_digitalocean_public_ipv4]
  regex: ^$, (.*)
  target_label: __address__
  replacement: "${1}:9100"
```

```hcl
// Prioritize private IPs
rule {
  source_labels = ["__meta_digitalocean_private_ipv4"]
  target_label  = "__address__"
  replacement   = "${1}:9100"
  action = "replace"
}

// Fallback to public IP only if private IP is missing
rule {
  source_labels = ["__meta_digitalocean_private_ipv4", "__meta_digitalocean_public_ipv4"]
  regex         = "^$, (.*)"
  target_label  = "__address__"
  replacement   = "${1}:9100"
  action = "replace"
}
```

### Configuration

```text

```

### Logs

```text

```
