### ISSUE TITLE
Grafana agent huge host resource utilization 

### ISSUE THREAD

**Issue by b0kky** [grafana/alloy#295]
### What's wrong?

Faced  with high CPU utilization on host by the grafana agent  (IOwait or SY).
By logs, we see  Prometheus and Promtail components  have some problems.
Use grafana-agent in docker, network_mode=host.
After rebooting container, the problem disappears ,therefore, restarting the container with the debug level on the problem host does not really help in diagnosing.
Can't get Pprof  at the time of the problem, grafana agent api not respond.

Example promtail:
`ts=2023-10-15T03:12:36.514004234Z caller=client.go:419 level=warn component=logs logs_config=local component=client host=loki-asia-front01.itrf.tech msg="error sending batch, will retry" status=-1 tenant= error="Post \"https://loki-asia-front01/loki/api/v1/push\": context deadline exceeded"
ts=2023-10-15T03:13:03.783121812Z caller=dedupe.go:112 agent=prometheus instance=8ae6f456b9a2666ff9496060a50cb339 component=remote level=warn remote_name=8ae6f4-b0971a url=https://metrics.sto-aws-stage/insert/0/prometheus/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://metrics.sto-aws-stage.itrf.tech/insert/0/prometheus/api/v1/write\": context deadline exceeded"`

This looks like a network issue but, while grafana-agent shown error in logs `msg="error sending batch, will retry" status=-1` 
endpoint loki-asia-front01 is avail and healthy. 
Example prometheus:
`ts=2023-09-29T05:41:28.555060542Z caller=dedupe.go:112 agent=prometheus instance=8ae6f456b9a2666ff9496060a50cb339 component=remote level=warn remote_name=8ae6f4-b0971a url=https://metrics.sto-aws-stage.itrf.tech/insert/0/prometheus/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://metrics.sto-aws-stage.itrf.tech/insert/0/prometheus/api/v1/write\": dial tcp 10.200.161.249:443: i/o timeout"`

Prometheus endpoint same as loki healthy and available.

Latest logs (only prometheus):
`ts=2023-12-04T08:25:04.531162449Z caller=dedupe.go:112 agent=prometheus instance=7e9527f8948db1b008afdfc2db12c2c4 component=remote level=warn remote_name=7e9527-2a7f5b url=https://metrics.sto-
aws-stage/insert/0/prometheus/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://metrics.sto-aws-stage/insert/0/prometheus/api/v1/write\": context deadli
ne exceeded"
ts=2023-12-04T08:25:06.517765622Z caller=dedupe.go:112 agent=prometheus instance=7e9527f8948db1b008afdfc2db12c2c4 component=remote level=warn remote_name=7e9527-2a7f5b url=https://metrics.sto-
aws-stage/insert/0/prometheus/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://metrics.sto-aws-stage/insert/0/prometheus/api/v1/write\": dial tcp 10.20
0.173.249:443: i/o timeout"`

**Curl from host:**
```
*  start date: Nov 27 09:18:38 2023 GMT
*  expire date: Feb 25 09:18:37 2024 GMT
*  subjectAltName: host "metrics.sto-aws-stage" matched cert's "*.sto-aws-stage"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* h2h3 [:method: POST]
* h2h3 [:path: /insert/0/prometheus/api/v1/import/csv?format=2:metric:ask,3:metric:bid,1:label:ticker,4:label:market]
* h2h3 [:scheme: https]
* h2h3 [:authority: metrics.sto-aws-stage]
* h2h3 [user-agent: curl/7.85.0]
* h2h3 [accept: */*]
* h2h3 [content-length: 19]
* h2h3 [content-type: application/x-www-form-urlencoded]
* Using Stream ID: 1 (easy handle 0x5633ba8b5870)
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> POST /insert/0/prometheus/api/v1/import/csv?format=2:metric:ask,3:metric:bid,1:label:ticker,4:label:market HTTP/2
> Host: metrics.sto-aws-stage
> user-agent: curl/7.85.0
> accept: */*
> content-length: 19
> content-type: application/x-www-form-urlencoded
> 
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* We are completely uploaded and fine
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
< HTTP/2 204 
< date: Mon, 04 Dec 2023 11:06:13 GMT
< vary: Accept-Encoding
< x-server-hostname: vm-cluster-victoria-metrics-cluster-vminsert-8884b95b5-dwf7t
< strict-transport-security: max-age=15724800; includeSubDomains
< 
* Connection #0 to host metrics.sto-aws-stage left intact
```

**Curl from container grafana-agent**

```
root@mongo02:/# curl -v  -d "GOOG,1.23,4.56,NYSE" 'https://metrics.sto-aws-stage/insert/0/prometheus/api/v1/import/csv?format=2:metric:ask,3:metric:bid,1:label:ticker,4:label:market'
*   Trying 10.200.167.249:443...
* Connected to metrics.sto-aws-stage (10.200.167.249) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=dev.2cash.ph
*  start date: Nov 27 09:18:38 2023 GMT
*  expire date: Feb 25 09:18:37 2024 GMT
*  subjectAltName: host "metrics.sto-aws-stage" matched cert's "*.sto-aws-stage"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: POST]
* h2h3 [:path: /insert/0/prometheus/api/v1/import/csv?format=2:metric:ask,3:metric:bid,1:label:ticker,4:label:market]
* h2h3 [:scheme: https]
* h2h3 [:authority: metrics.sto-aws-stage]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* h2h3 [content-length: 19]
* h2h3 [content-type: application/x-www-form-urlencoded]
* Using Stream ID: 1 (easy handle 0x55a53cb8d670)
> POST /insert/0/prometheus/api/v1/import/csv?format=2:metric:ask,3:metric:bid,1:label:ticker,4:label:market HTTP/2
> Host: metrics.sto-aws-stage
> user-agent: curl/7.88.1
> accept: */*
> content-length: 19
> content-type: application/x-www-form-urlencoded
> 
* We are completely uploaded and fine
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 204 
< date: Mon, 04 Dec 2023 11:08:55 GMT
< vary: Accept-Encoding
< x-server-hostname: vm-cluster-victoria-metrics-cluster-vminsert-8884b95b5-9vs5b
< strict-transport-security: max-age=15724800; includeSubDomains
< 
* Connection #0 to host metrics.sto-aws-stage left intact
```
No problem with endpoint =\

If need some data about compose\docker\hosts, or something else - let me know. 

### Steps to reproduce

Can't to reproduce, will try to block promtail or prometheus, by iptables, got same error in logs but utilization not huge/ 

### System information

Linux mongo02-kz 6.0.7-301.fc37.x86_64

### Software version

grafana agent v0.37.2 

### Configuration

```text
Docker version:
Client:
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:14:26 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:20:17 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d1
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jsixface** [comment]
I have the similar issue where alloy uses more CPU resource for `iowait`. I have a VM where Alloy is a container along with couple of other containers. I use alloy to collect the logs and forward them to Loki over Tailscale VPN. The below image is before  and after I stopped the alloy container after the high CPU usage for `iowait`

<img width="1272" alt="Image" src="https://github.com/user-attachments/assets/d529fd59-4e16-4b7f-81b6-7669c70ba089" />

**Comment by b0kky** [comment]
@jsixface could you share config and compose files?

**Comment by jsixface** [comment]
@b0kky Sure. I just wanna add that this is a recurring problem on this one VM (hosted on OCI). I have another VM there that doesn't have this issue. I've also have a physical server that also doesn't have this issue.  Here's `config.alloy`:
```
discovery.docker "container_logs" {
	host             = "unix:///var/run/docker.sock"
	refresh_interval = "5s"
}
discovery.relabel "container_logs" {
	targets = []
	rule {
		source_labels = ["__meta_docker_container_name"]
		regex         = "/(.*)"
		target_label  = "container"
	}
	rule {
		source_labels = ["__address__"]
		target_label  = "host"
		replacement   = "sodium"
	}
}
loki.source.docker "container_logs" {
	host             = "unix:///var/run/docker.sock"
	targets          = discovery.docker.container_logs.targets
	forward_to       = [loki.write.default.receiver]
	relabel_rules    = discovery.relabel.container_logs.rules
	refresh_interval = "5s"
}
loki.write "default" {
	endpoint {
		url = "http://log-collector.ts.net:3100/loki/api/v1/push"
	}
	external_labels = {}
}
```
And here's `compose.yaml`. 
```yaml
name: sodium
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    user: ${USER_ID:?error}
    expose:
      - "5432"
    volumes:
      - ${DATA?:error}/postgres:/var/lib/postgresql/data:z
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?required}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 250M
# ------ Bit Warden ---------
  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server:alpine
    restart: unless-stopped
    user: ${USER_ID:?error}
    volumes: 
      - $DATA/bitwarden:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${TAILSCALE_IP:?error}:8089:80"
    depends_on:
      - postgres
    environment:
      WEBSOCKET_ENABLED: "true"  # Enable WebSocket notifications.
# ------ Supporting services ---------
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    privileged: true
    user: telegraf:988 #988 = docker's gid
    restart: unless-stopped
    volumes:
     - ${CONFIG}/telegraf:/etc/telegraf:ro
     - /:/hostfs:ro
     - /etc/localtime:/etc/locfltime:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
     - HOST_ETC=/hostfs/etc
     - HOST_PROC=/hostfs/proc
     - HOST_SYS=/hostfs/sys
     - HOST_VAR=/hostfs/var
     - HOST_RUN=/hostfs/run
     - HOST_MOUNT_PREFIX=/hostfs
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 125M
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - /var/log:/var/log
      - /run/log:/run/log
      - /etc/machine-id:/etc/machine-id
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG}/alloy:/config
      - alloy-data:/data
    command: run --disable-reporting --storage.path=/data /config/config.alloy
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 125M

volumes:
  alloy-data:
    name: alloy-data-volume
```

**Comment by b0kky** [comment]
@jsixface great, thanks. I have a little bit workaround with CPU utilization by grafana agent, but i think alloy have same problems and reasons and you colud try next:
1.  disable limits for container (CPU and RAM), try remove deploy limits, go have own GC, becomes near limits, , and may trigger utilize CPU
`    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 125M`

2.  add drop older logs files 
```yaml
- drop:
    older_than: 30m
    drop_counter_reason: reject_old_samples
```
sometimes promtail can't push logs at loki at time, queue is growing and if you have some limits on container, it will be call GC often and often

3. in discovery section  refresh_interval = "5s", this too often, try with 30s
