### ISSUE TITLE
mimir.rules.kubernetes cannot parse expressions with durations

### ISSUE THREAD

**Issue by armsnyder** [grafana/alloy#2979]
### What's wrong?

I have a RecordingRule which is valid in Prometheus but cannot be parsed by Alloy. The query uses a duration in an expression: `probe_ssl_earliest_cert_expiry < time() + 29d`.

This is the relevant Prometheus feature that allows using durations in queries: https://github.com/prometheus/prometheus/pull/15111

### Steps to reproduce

Minimal PrometheusRule to reproduce:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: myrule
spec:
  groups:
  - name: mygroup
    rules:
    - alert: CertificateExpiresSoon
      expr: probe_ssl_earliest_cert_expiry < time() + 29d
```

### Software version

Alloy v1.6.1

### Configuration

```text
mimir.rules.kubernetes "default" {
  address = "redacted"
  tenant_id = "redacted"
  mimir_namespace_prefix = "redacted"
}
```

### Logs

```text
failed to convert rule group: 2 errors occurred:
	* 11:11: group "mygroup", rule 1, "CertificateExpiresSoon": could not parse expression: 1:43: parse error: unexpected duration "29d"
```
