### ISSUE TITLE
kind: Integration How to display node_ip in Dashboard？

### ISSUE THREAD

**Issue by 1473371932** [grafana/alloy#299]
### What's wrong?

Hello, I have a question: After deploying the Grafana-agent through the operator, and then deploying `kind: Integration`, when using the node_exporter template in the Grafana Dashboard, such as ID 1860, it displays node_name instead of node_ip. I have tried changing the Integration configuration file：

```
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  ......
spec:
  ......
    config:
    autoscrape:
      ......
      relabel_configs:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels: ["__meta_kubernetes_pod_node_NodeInternalIP"]
          target_label: instance
```

In the node_exporter within prometheus-operator, using this tag can retrieve the node_ip. However, in kind: Integration, the result obtained is: instance = agent.internal:12345,

According to the official website: https://grafana.com/docs/agent/latest/static/api/#agent-api, using GET /agent/api/v1/metrics/targets allows you to access all metric information, 

After creating kind: Integration, a Pod named grafana-agent-integrations-ds is generated. I believe the requests should be directed to this Pod instead of grafana-agent-0, but the results are different from what I expected:

```
± kubectl get pods -n deepflow -o wide | grep grafana-agent    
grafana-agent-0                                         2/2     Running   0             5h50m   100.79.96.206
grafana-agent-grafana-agent-operator-64ff4bf5cd-rz66v   1/1     Running   0             5h51m   100.79.96.236
grafana-agent-integrations-ds-rkt4d                     2/2     Running   0             38m     100.79.96.210

## Requesting the grafana-agent-integrations-ds Pod did not retrieve any content
± curl -X GET 100.79.96.210:8080/agent/api/v1/metrics/targets
{"status":"success","data":[]}#

## whereas the result of requesting grafana-agent-0 was:
## The target_group is kube-state-metrics, which is unrelated to Integration
± curl -X GET 100.79.96.206:8080/agent/api/v1/metrics/targets
{
    "status":"success",
    "data":[
        {
            "instance":"e888f49aaf528e9159259aa8f99b8fd3",
            "target_group":"serviceMonitor/deepflow/kube-state-metrics/0",
            "endpoint":"https://100.79.96.199:8443/metrics",
            "state":"up",
            "labels":Object{...},
            "discovered_labels":{
                ......
                "__meta_kubernetes_pod_host_ip":"10.1.5.4",
                ......
                "__meta_kubernetes_service_name":"kube-state-metrics",
                "__metrics_path__":"/metrics",
                "__scheme__":"[https](https://www.json.cn/https)",
                "__scrape_interval__":"25s",
                "__scrape_timeout__":"10s",
                "job":"serviceMonitor/deepflow/kube-state-metrics/0"
            },
            ......
        },
        {
            ......
            "target_group":"serviceMonitor/deepflow/kube-state-metrics/1",
            "endpoint":"https://100.79.96.199:9443/metrics",
            "state":"up",
            ......
            "discovered_labels":Object{...},
            ......
        }
    ]
}
```

Therefore, even if the `sourceLabels` in the `kind: Integration` configuration is changed to `__meta_kubernetes_pod_host_ip`, it still does not take effect:

```
apiVersion: monitoring.grafana.com/v1alpha1
kind: Integration
metadata:
  ......
spec:
  ......
  config:
    autoscrape:
      ......
      relabel_configs:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels: ["__meta_kubernetes_pod_host_ip"]
          target_label: instance
```

After numerous attempts, I have not been able to identify the cause... However, in the node_exporter configuration file for Prometheus, the value of `hostNetwork is 'true'`. I haven't found this parameter in `kind: GrafanaAgent` or `kind: Integration` I wonder if this might be the reason?

### Steps to reproduce

none

### System information

Linux CentOS 7 5.4.256-1.el7.elrepo.x86_64

### Software version

grafana-agent:v0.37.4
