### ISSUE TITLE
Grafana agent support runAsNonRoot

### ISSUE THREAD

**Issue by HSoulat** [grafana/alloy#303]
### Request

Grafana agent should runAsNonRoot in order to follow [Kubernetes Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/). 

Currently use runAsNonRoot is not permited and if we set runAsUser the agent do not work correctly. 

### Use case

Some use case do not require to run the Agent as root.

**Comment by captncraig** [comment]
There is a user id 473 inside the container now, that should have ownership over the files it needs. I've had some success setting runAsUser, runAsGroup, and fsGroup to 473. I am not sure if it can run with dropping all capabilities though, as the default agent port is 80, which needs a flag on the binary.

**Comment by bcrisp4** [comment]
> There is a user id 473 inside the container now, that should have ownership over the files it needs. I've had some success setting runAsUser, runAsGroup, and fsGroup to 473. I am not sure if it can run with dropping all capabilities though, as the default agent port is 80, which needs a flag on the binary. 

I believe the default port has changed to 12345 with the rebranding to Alloy. Or at least in the Helm chart it has.

**Comment by bcrisp4** [comment]
Deploying Alloy with the Helm chart with the following values seems to work fine

```yaml
global:
  podSecurityContext:
    runAsUser: 473
    runAsGroup: 473
    fsGroup: 473
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
```

Dropping all capabilities does not work, as you suspected. I get the following when the pod starts:
```
exec /bin/alloy: operation not permitted
```

**Comment by bcrisp4** [comment]
Looks like it just needs `NET_BIND_SERVICE`
```
alloy@tenant-monitoring-platform-ks-core-alloy-0:/$ grep Cap /proc/1/status
CapInh: 0000000000000000
CapPrm: 0000000000000400
CapEff: 0000000000000400
CapBnd: 00000000a80425fb
CapAmb: 0000000000000000
alloy@tenant-monitoring-platform-ks-core-alloy-0:/$ capsh --decode=0000000000000400
0x0000000000000400=cap_net_bind_service
```
So this works fine:
```yaml
securityContext:
  ...
  capabilities:
    drop: ["ALL"]
    add: ["NET_BIND_SERVICE"]
```
