### ISSUE TITLE
Dedup exporters and connectors in the otel converter

### ISSUE THREAD

**Issue by wildum** [grafana/alloy#3045]
When the same exporter/connector is used in different pipelines, we currently duplicate it instead of reusing it:

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: database:4317

service:
  pipelines:
    metrics: # Group <empty>
      receivers: [otlp]
      processors: []
      exporters: [otlp]
    metrics/2: # Group 2
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
```

In this case, there should only be one otlp exporter generated in Alloy.

This is what the Otel collector does: https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/internal/graph/graph.go#L236
