### ISSUE TITLE
discovery.docker does not detect new docker containers sometimes and instead tries to read logs from old containers indefinitely

### ISSUE THREAD

**Issue by saibotma** [grafana/alloy#3054]
### What's wrong?

Logs error (see logs below) many times until I restart alloy.
The container `3e280a7cc524c0d739851137102b43cd5afccee42c80db1ee1959d30db56b2f4` got removed, and another one got created instead. The new one is not discovered, though.

### Steps to reproduce

Can not reproduce it every time unfortunately, however basically:

1. Run Alloy in Docker
2. Start a Docker container
3. Stop the Docker container
4. Remove the Docker container
5. Start a new Docker container
6. Notice that Alloy does not remove the old and/or add the new one.

### System information

Ubuntu 24.04.1 LTS aarch64

### Software version

Grafana Alloy 1.7.5, Docker 27.4.1

### Configuration

`docker-compose.yml`:

```
version: "3"
services:
  alloy:
    image: grafana/alloy:v1.7.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/nginx:/var/log/nginx
      - /var/log/remote:/var/log/remote
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./config.alloy:/etc/alloy/config.alloy
      - alloy-data:/var/lib/alloy
    restart: unless-stopped
    command: run --storage.path=/var/lib/alloy /etc/alloy/config.alloy

volumes:
  alloy-data:
```

`config.alloy`:

```
discovery.docker "docker_containers" {
	host = "unix:///var/run/docker.sock"
}

discovery.relabel "docker_containers" {
	targets = discovery.docker.docker_containers.targets

	rule {
		source_labels = ["__meta_docker_container_name"]
		regex         = "/(.*)"
		target_label  = "container_name"
	}
}

loki.source.docker "docker_containers" {
	host          = "unix:///var/run/docker.sock"
	targets       = discovery.relabel.docker_containers.output
	labels        = {"job" = "docker-containers"}
	forward_to    = [loki.write.default.receiver]
	relabel_rules = discovery.relabel.docker_containers.rules
}

loki.write "default" {
	endpoint {
		url = "x"

		basic_auth {
			username = "x"
			password = "x"
		}
	}
	external_labels = {
		env      = "production",
		hostname = "x",
	}
}
```

### Logs

```console
ts=2025-03-21T09:08:24.384360077Z level=error msg="error inspecting Docker container" target=3e280a7cc524c0d739851137102b43cd5afccee42c80db1ee1959d30db56b2f4 component_path=/ component_id=loki.source.docker.docker_containers id=3e280a7cc524c0d739851137102b43cd5afccee42c80db1ee1959d30db56b2f4 error="Error response from daemon: No such container: 3e280a7cc524c0d739851137102b43cd5afccee42c80db1ee1959d30db56b2f4"
```
