### ISSUE TITLE
Please support DNS service discovery modes similar to Mimir, Loki, Tempo, and Pyroscope

### ISSUE THREAD

**Issue by chewrocca** [grafana/alloy#3174]
### Request

https://grafana.com/docs/alloy/latest/reference/cli/run/#clustering says it supports DNS SRV but it doesn't appear to work the same way as the DNS service discovery modes in Mimir, Tempo, Loki, and Pyroscope.  https://grafana.com/docs/mimir/latest/configure/about-dns-service-discovery/#supported-discovery-modes

### Use case

It would be great to use `dnssrvnoa+` in Alloy clustering.  Something along these lines:

`--cluster.join-addresses="dnssrvnoa+_alloy-memberlist._tcp.service.consul"`

**Comment by x1unix** [comment]
@chewrocca what setup are you using for DNS?

**Comment by chewrocca** [comment]
We're using Consul DNS.  I would like to use dnssrvnoa+ to cluster Alloy. In the Memberlist configurations for the other services like Mimir, Loki, and Tempo, we can target using the dnssrvnoa+ method.

**Comment by x1unix** [comment]
@chewrocca I'm working on a PR to implement that - https://github.com/grafana/alloy/pull/5034

Please note that you would need to manually specify all your Alloy instances in Consul members list and configure your containers to use Consul as DNS.

For example:

<details>
<summary><code>/etc/consul/config/alloy.json</code></summary>

```json
{
  "services": [
    {
      "id": "alloy0",
      "name": "alloy-memberlist",
      "port": 12345,
      "address": "alloy0",
      "tags": [
        "alloy",
        "memberlist"
      ]
    },
    {
      "id": "alloy1",
      "name": "alloy-memberlist",
      "port": 12345,
      "address": "alloy1",
      "tags": [
        "alloy",
        "memberlist"
      ]
    }
  ]
}
```

</details>

<details>
<summary><code>compose.yml</code></summary>

```yaml
x-alloy-image: &alloy-image
  image: grafana/alloy:v1.12.0
  command: >
    run
      --cluster.enabled=true
      --cluster.join-addresses=dnssrvnoa+_alloy-memberlist._tcp.service.consul
      ...
      config.alloy
  dns:
    - 10.3.0.10
    - 8.8.8.8
  dns_search:
    - service.consul
  depends_on:
    - consul
  networks:
    - consul

services:
  consul:
    image: hashicorp/consul:1.15
    command: >
      agent -server 
      -ui 
      -bootstrap-expect=1
      -client=0.0.0.0 -bind=0.0.0.0
      -data-dir=/consul
      -config-dir=/etc/consul/config
      -dns-port=53
    ports:
      - "8500:8500"
    volumes:
      - ./etc/consul:/etc/consul/config:ro
      - consul:/consul
    networks:
      consul:
        ipv4_address: 10.3.0.10

  alloy0:
    <<: *alloy-image
    hostname: alloy0

  alloy1:
    <<: *alloy-image
    hostname: alloy1

  alloy2:
    <<: *alloy-image
    hostname: alloy2

networks:
  consul:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.0.0/16

volumes:
  consul:

```

</details>
