### ISSUE TITLE
Unable to expose Faro port using ingress

### ISSUE THREAD

**Issue by ChinthapalliNikhithaChandana** [grafana/alloy#3283]
### What's wrong?

Trying to expose Faro port 12347 using traefik ingress, but it gives 404 error.

### Steps to reproduce
Used grafana Alloy helm chart https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/values.yaml

### Software version

Grafana alloy v1.7

### Configuration

```yaml  

      otelcol.receiver.otlp "otlp" {
        grpc {
          endpoint = "0.0.0.0:4317"
        }
        http {
            endpoint = "0.0.0.0:4318"
            cors {
              allowed_origins = ["*"]
              allowed_headers = ["authorization", "content-type"]
            }
          }
          output {
            logs    = [otelcol.processor.batch.otlp.input]
            traces = [otelcol.processor.batch.otlp.input]
            metrics = [otelcol.processor.batch.otlp.input]
          }
      }

      faro.receiver "default" {
        log_format = "logfmt"
        server {
          listen_address = "0.0.0.0"
          listen_port = "12347"
          cors_allowed_origins = ["*"]
        }
        output {
          logs   = [loki.process.process.receiver]
          traces = [otelcol.processor.batch.otlp.input]
        }
      }

  extraPorts:
    - name: otlphttp
      port: 4318
      targetPort: 4318
    - name: otlpgrpc
      port: 4317
      targetPort: 4317
    - name: faro
      port: 12347
      targetPort: 12347
      protocol: "TCP"

ingress:
  enabled: true
  ingressClassName: traefik
  annotaions:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels: {}
  path: /
  faroPort: 12345
  pathType: Prefix
  hosts:
    - alloy.righive.local
  extraPaths:
    - path: /v1/logs
      pathType: Prefix
      backend:
        service:
          name: alloy
          port:
            number: 4318
    - path: /v1/traces
      pathType: Prefix
      backend:
        service:
          name: alloy
          port:
            number: 4318
    - path: /v1/metrics
      pathType: Prefix
      backend:
        service:
          name: alloy
          port:
            number: 4318
     - path: /faro
       pathType: Prefix
       backend:
         service:
           name: alloy
           port:
             number: 12347
```

### Logs

```text

```
