### ISSUE TITLE
loki.source.podlogs - pod labels not present anymore

### ISSUE THREAD

**Issue by fnerdwq** [grafana/alloy#3311]
### What's wrong?

Starting with alloy 1.8.0 (also in 1.8.1) the `__meta_kubernetes_pod_label_*` discovered_labels are not present anymore. for `loki.source.podlogs` resources. Up to 1.7.5 this was working perfectly.
(Also `__meta_kubernetes_namespace` is missing now - but this didn't hit us...)

All other discovered_labels are present (pod labesl etcpp),e ven the `__meta_kubernetes_pod_labelpresent_*` are all correctly present.

Here a diff of what is missing in our case since v1.8.0

![Image](https://github.com/user-attachments/assets/b2619815-2bcf-4216-a287-fd1512f87a05)

### Steps to reproduce

We are using a podlogs defintion like this:

```
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  labels:
    environment: int
    region: someRegion
  name: podlogs-someNamespace
  namespace: someNamespace
spec:
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - someNamespace
  relabelings:
  - action: replace
    sourceLabels:
    - __meta_kubernetes_pod_label_app
    targetLabel: app
  selector:
    matchLabels:
      A: "true"
```

### System information

Kubernetes 1.32

### Software version

Grafana Alloy v1.8.0/v1.8.1

### Configuration

```text
loki.source.podlogs "default" {
    forward_to = [loki.relabel.default.receiver]

    namespace_selector {
        match_expression {
            key      = "name"
            operator = "In"
            values   = argument.namespaces.value
        }
    }

    selector {
        match_expression {
            key      = "app.kubernetes.io/name"
            operator = "NotIn"
            values   = ["obsrv-generator"]
        }
    }

    clustering {
        enabled = true
    }
}

loki.relabel "default" {
    forward_to = [customer.process.default.receiver]

    rule {
        source_labels = ["instance"]
        regex         = "(.+)/(.+):(.+)"
        replacement   = "$1"
        target_label  = "namespace"
    }

    rule {
        source_labels = ["instance"]
        regex         = "(.+)/(.+):(.+)"
        replacement   = "$2"
        target_label  = "pod"
    }

    rule {
        source_labels = ["instance"]
        regex         = "(.+)/(.+):(.+)"
        replacement   = "$3"
        target_label  = "container"
    }

    rule {
        regex  = "instance"
        action = "labeldrop"
    }
}
```

### Logs

```text

```
