### ISSUE TITLE
Prometheus Operator ScrapeConfig CRD support creates invalid scrape_config

### ISSUE THREAD

**Issue by larslevie** [grafana/alloy#3386]
The new Prometheus Operator `ScrapeConfig` CRD support fails with the following error when processing the `prometheus.operator.scrapeconfigs` directive:

```
msg="Creating target failed" component_path=/ component_id=prometheus.operator.scrapeconfigs.scrape_configs scrape_pool=scrapeConfig/lead-router/lead-router-rabbitmq/static/0 err="instance 0 in group scrapeConfig/lead-router/lead-router-rabbitmq/static/0: invalid scheme: "HTTPS""
```

## Root Cause
The error originates from Mimir's validation ([source](https://github.com/grafana/mimir/blob/main/vendor/github.com/prometheus/prometheus/scrape/scrape.go#L472-L474)).

The issue occurs because:
1. Prometheus Operator `ScrapeConfig` CRD requires `spec.scheme` to be uppercase `HTTP` or `HTTPS`
2. Prometheus/Mimir expect lowercase `http` or `https` in the final scrape configuration

This may be a Mimir-specific issue; I haven't tested with pure Prometheus.

## Proposed Fix
Downcase the `scheme` value [here](https://github.com/grafana/alloy/blob/main/internal/component/prometheus/operator/configgen/config_gen_scrapeconfig.go#L95) when copying it to the native Prometheus scrape config object. I'm game to submit a PR, but before I do that I figured I'd validate the issue. Maybe I'm just doing something wrong. 😄 

## Example ScrapeConfig causing the error:
  
```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: lead-router-rabbitmq
spec:
  jobName: am12-lead-router-rabbitmq0
  basicAuth:
    username:
      name: lead-router-rabbitmq-prom-secret
      key: username
    password:
      name: lead-router-rabbitmq-prom-secret
      key: password
  scheme: HTTPS
  metricsPath: /metrics
  staticConfigs:
    - targets:
        - merry-red-prawn-01.rmq4.cloudamqp.com
        - merry-red-prawn-02.rmq4.cloudamqp.com
        - merry-red-prawn-03.rmq4.cloudamqp.com
```

### System information

docker.io/grafana/alloy:v1.8.1

### Software version

Alloy v1.8.1, grafana-k8s-monitoring Helm chart v2.0.24

### Configuration

```text
...

prometheus.operator.scrapeconfigs "scrape_configs" {
  clustering {
    enabled = true
  }
  scrape {
    default_scrape_interval = "15s"
  }
  forward_to = [prometheus.remote_write.mimir_witco.receiver]
}
```

### Logs

```text
msg="Creating target failed" component_path=/ component_id=prometheus.operator.scrapeconfigs.scrape_configs scrape_pool=scrapeConfig/lead-router/lead-router-rabbitmq/static/0 err="instance 0 in group scrapeConfig/lead-router/lead-router-rabbitmq/static/0: invalid scheme: "HTTPS""
```
