### ISSUE TITLE
loki.source.docker will not start collecting logs from containers not in the "running" state

### ISSUE THREAD

**Issue by RasEza** [grafana/alloy#3408]
### What's wrong?

The `loki.source.docker` component will not start collecting logs for containers not in the "running" state.

This means that logs from short lived containers will never be collected, such as those produced by the [hello-world](https://hub.docker.com/_/hello-world) image. Additionally when running containers in Swarm Mode, containers that are stuck in a restart loop will not have their logs collected. When deploying containers as services in Swarm Mode a brand new container will be started each time a restart is attempted.

I believe this is a regression introduced with the following PR: 
https://github.com/grafana/alloy/pull/742 and is present from version v1.1.0 onward.

Specifically the following lines:
https://github.com/grafana/alloy/pull/742/files#diff-d874c83bf4c47ce716a3181d51c95e1a1093f2c5515c802053eef66404a7db6aR106-R114

The consequence of this issue is that `loki.source.docker` is unsuitable for use in production as critical logs may not be collected and forwarded to Loki.

### Steps to reproduce

The following POC demonstrates in a Grafana instance that logs are not written to Loki by Alloy when using an Alloy version beyond v1.0.0 and that they are collected when using v1.0.0.

Prerequisites:
A Docker installation with Swarm Mode enabled

Steps:

1. Create the files below and ensure that they are placed in the same folder
2. Execute `docker stack deploy restarting_stack -c docker-compose.yml` from the folder 
3. Open Grafana on `localhost:3000` and login using the default credentials `admin:admin`
4. Navigate to the explore tab and select the Loki datasource
5. Execute the following query against the Loki datasource "{service_name="restarting_stack_restarting-service"} |= ``"
6. Note that no logs are collected
7. Comment in `image: docker.io/grafana/alloy:v1.0.0` in the dokcer-compose.yml file and comment out `image: docker.io/grafana/alloy:v1.8.0`
8. Execute `docker stack deploy restarting_stack -c docker-compose.yml` from the folder 
9. Note that logs start to be collected

docker-compose.yaml
```yaml
services:
  restarting-service:
    image: docker.io/hello-world
    deploy:
      restart_policy:
        condition: any
        delay: 5s

  alloy:
    image: docker.io/grafana/alloy:v1.8.0
    # image: docker.io/grafana/alloy:v1.0.0
    ports:
      - target: 9080
        published: 9080
        mode: host
        protocol: tcp
    command:
      - run
      - /config.alloy
    volumes:
      - ./config.alloy:/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
  loki:
    image: docker.io/grafana/loki:3.3.2

  grafana:
    image: docker.io/grafana/grafana:11.5.1
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - target: 3000
        published: 3000
        mode: host
        protocol: tcp

```

datasource.yaml
```yaml
apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: false
    basicAuth: false

```

config.alloy
```
discovery.docker "docker_log_scrape" {
	host             = "unix:///var/run/docker.sock"
	refresh_interval = "5s"

	filter {
		name   = "status"
		values = ["running", "exited", "dead", "created", "paused", "restarting", "removing"]
	}
}

loki.source.docker "docker_log_scrape" {
	host             = "unix:///var/run/docker.sock"
	targets          = discovery.docker.docker_log_scrape.targets
	forward_to       = [loki.write.default.receiver]
	relabel_rules    = discovery.relabel.docker_log_scrape.rules
	refresh_interval = "10s"
}

loki.write "default" {
	endpoint {
		url = "http://loki:3100/loki/api/v1/push"
	}
}

discovery.relabel "docker_log_scrape" {
	targets = []

	rule {
		source_labels = ["__meta_docker_container_name"]
		target_label  = "container"
	}

	rule {
		source_labels = [
			"__meta_docker_container_label_com_docker_swarm_service_name",
		]
		target_label = "service_name"
	}
}
```

### Software version

Grafana Alloy v1.1+

### Configuration

```text
discovery.docker "docker_log_scrape" {
	host             = "unix:///var/run/docker.sock"
	refresh_interval = "5s"

	filter {
		name   = "status"
		values = ["running", "exited", "dead", "created", "paused", "restarting", "removing"]
	}
}

loki.source.docker "docker_log_scrape" {
	host             = "unix:///var/run/docker.sock"
	targets          = discovery.docker.docker_log_scrape.targets
	forward_to       = [loki.write.default.receiver]
	relabel_rules    = discovery.relabel.docker_log_scrape.rules
	refresh_interval = "10s"
}

loki.write "default" {
	endpoint {
		url = "http://loki:3100/loki/api/v1/push"
	}
}

discovery.relabel "docker_log_scrape" {
	targets = []

	rule {
		source_labels = ["__meta_docker_container_name"]
		target_label  = "container"
	}

	rule {
		source_labels = [
			"__meta_docker_container_label_com_docker_swarm_service_name",
		]
		target_label = "service_name"
	}
}
```

### Logs

```text

```
