### ISSUE TITLE
VPA Helm templating issue

### ISSUE THREAD

**Issue by randori-jgross** [grafana/alloy#3436]
### What's wrong?

I believe that this chart needs the range function adjusted:

https://github.com/grafana/alloy/blob/main/operations/helm/charts/alloy/templates/vpa.yaml#L19-L23

Current output creates this incorrect spec:

```
spec:
  resourcePolicy:
    containerName: alloy
    containerPolicies: null
    controlledResources:
      - cpu
      - memory
    controlledValues: RequestsAndLimits
    maxAllowed: {}
    minAllowed: {}
```

### Steps to reproduce

Template or install the chart with this value:

```
.Values.controller.autoscaling.vertical.enabled: true
```

### Software version

Alloy v1.0.2

### Configuration

```text

```

### Logs

```text

```
