### ISSUE TITLE
PodLogs relabeling (labelkeep) does not preserve mandatory labels like "__pod_namespace__" or "__meta_kubernetes_namespace"

### ISSUE THREAD

**Issue by yogeek** [grafana/alloy#3520]
### What's wrong?

As explained in [this comment](https://github.com/grafana/alloy/pull/3334#issuecomment-2855573219), some mandatory labels are not kept when using relabeling in PodLogs, in particular with `labelkeep` action.
This cause an error that prevent logs to be sent to loki.

cf. @kalleep explanation in https://grafana.slack.com/archives/C01050C3D8F/p1746603691754399?thread_ts=1746557320.089289&cid=C01050C3D8F

### Steps to reproduce

- Install Alloy 1.8.2 from chart in kubernetes
- Set up alloy config to detect PodLogs CR:
```
loki.source.podlogs "podlogs_crd" {
  forward_to = [loki.write.gtp_loki.receiver]
  namespace_selector {
        match_expression {
            key = "logs_enabled"
            operator = "In"
            values = ["true"]
        }
    }
}
loki.write "gtp_loki" {
    endpoint {
        url = "http://loki-gateway.loki/loki/api/v1/push"
    }
}
```
- Create a PodLog CR :
```
# Select all pods in alloy namespaces
apiVersion: monitoring.grafana.com/v1alpha2
kind: PodLogs
metadata:
  name: test-alloy
spec:
  selector: {}
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
        - alloy
  relabelings:
  - sourceLabels: [__meta_kubernetes_pod_node_name]
    targetLabel: node
  - sourceLabels: [__meta_kubernetes_namespace]
    targetLabel: namespace
  - sourceLabels: [__meta_kubernetes_pod_container_name]
    targetLabel: container
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - sourceLabels: [app_kubernetes_io_name]
    targetLabel: app
  # when removing the following action, it worked correctly but all labels are keptn, which is not desired
  - action: "labelkeep"
    regex: "node|namespace|container|app"
```

With the "labelkeep" action, no logs are present in Loki and in Alloy's debug UI, the error message is

```
reconcile_error  "invalid labels: missing pod namespace label"
```

### System information

Kubernetes 1.29.4 / Ubuntu 1.22

### Software version

Grafana Alloy 1.8.2

### Configuration

```text

```

### Logs

```text

```
