### ISSUE TITLE
Fluentforward component support

### ISSUE THREAD

**Issue by gwicks** [grafana/alloy#3529]
### Request

I would like to be able to leverage the `fluentforward` component found in many `otel-collector` community distributions.

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/fluentforwardreceiver/README.md

This is an essential part of my current workflow for log ingestion, since it allows me to use the lower level container logs instead of relying on the OTEL SDK to capture logging. Obivously some semantics would need to be implemented to configure this, and I am open to taking a crack at this myself.

Maybe something like

```
loki.receiever.fluentforward "example" {
     endpoint = "unix:///var/run/fluent.sock"

    forward_to = [loki.process.resourceattrs]
}
```

### Use case

My current workflow relies on AWS Firelens to be able to forward logs, here's a snippet from one of my config files for OTEL Collector for reference. In AWS Fargate, it gets exposed as a file located in `/var/run/fluent.sock`. I add all the metadata elsewhere in the config file (which is well within Alloys existing capabilities).

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"
  fluentforward:
    endpoint: unix:///var/run/fluent.sock
...

service:
  pipelines:
    logs:
      receivers: [fluentforward]
      processors: [resource, resource/loki, batch]
      exporters: [loki]
```
