### ISSUE TITLE
How can we avoid collecting logs repeatedly when deploying alloy using the deployment method

### ISSUE THREAD

**Issue by vitaaaaa1** [grafana/alloy#3533]
### What's wrong?

How can we avoid collecting logs repeatedly when deploying alloy using the deployment method
```
controller:
  # -- Type of controller to use for deploying Grafana Alloy in the cluster.
  # Must be one of 'daemonset', 'deployment', or 'statefulset'.
  type: 'daemonset'

  # -- Number of pods to deploy. Ignored when controller.type is 'daemonset'.
  replicas: 3
```

### Steps to reproduce

.

### Configuration

```text

```

### Logs

```text

```
