### ISSUE TITLE
Otel converters should use backticks instead of escaping double quotes

### ISSUE THREAD

**Issue by wildum** [grafana/alloy#3690]
This is what the converter generates now:
"resource.attributes[\\"service.name\\"] == \\"unknown_service\\""

For better readability, the converter could use backticks:
\`resource.attributes["service.name"] == "unknown_service"\`

This would match better with the otel format:

```
processors:
  filter/drop_unwanted_telemetry:
    logs:
      log_record:
        - 'resource.attributes["service.name"] == "unknown_service"'
```
