### ISSUE TITLE
higher memory usage with intergration exporter

### ISSUE THREAD

**Issue by lovesharepc** [grafana/alloy#372]
### What's wrong?

here is I use docker to test memory usage 

docker stats
```
a420f8086a30   grafana_agent_compare-otelcol-1          0.07%     97.17MiB / 31.11GiB   0.31%     22.2MB / 31.3MB   0B / 0B       14
4f61a58af866   grafana_agent_compare-node-exporter-1    0.00%     9.176MiB / 31.11GiB   0.03%     541kB / 17.1MB    0B / 0B       6
525088fff6ed   grafana_agent_compare-prometheus-1       0.28%     90.14MiB / 31.11GiB   0.28%     22.2MB / 25.2MB   0B / 4.97MB   13
d581ac402ca2   grafana_agent_compare-grafana-agent1-1   18.62%    208MiB / 31.11GiB     0.65%     448kB / 29.4MB    0B / 4.88MB   18
ce898edd8882   grafana_agent_compare-grafana-agent-1    1.72%     99.95MiB / 31.11GiB   0.31%     22.5MB / 26.3MB   0B / 4.71MB   13
ce1de29041c0   grafana_agent_compare-cadvisor-1         1.74%     58.14MiB / 31.11GiB   0.18%     12.4MB / 808MB    0B / 0B       16
36595ae144a1   grafana_agent_compare-fluent-bit-1       11.56%    46.28MiB / 31.11GiB   0.15%     760MB / 79.5MB    201kB / 0B    5
```

the container `grafana_agent_compare-grafana-agent1-1 ` use intergration exporter 
the container `grafana_agent_compare-grafana-agent-1 ` use external exporter 
both scrape  cadvisor and node-exporter

memory usage
use intergration exporter: 208 MiB
use external exporter: 58.14(cadvisor) + 9.176(node exporter) + 99.95(agent) = 167.266 MiB

grafana_agent_compare-grafana-agent1-1 config (intergration exporter)
```
server:
  log_level: info

metrics:
  global:
    scrape_interval: 15s
    external_labels:
      node_name: grafana-agent

    remote_write:
      - url: https://192.168.100.152:8095/api/v1/push
        tls_config:
          insecure_skip_verify: true
        headers:
          X-Scope-OrgID: test
        basic_auth:
          username: test
          password: test

  wal_directory: "/var/lib/grafana-agent"
  wal_cleanup_age: "12h"
  configs:
 

# https://grafana.com/docs/agent/latest/configuration/integrations/
integrations:
  agent:
    enabled: false
  node_exporter:
    enabled: true

  cadvisor:
    enabled: true
```

grafana_agent_compare-grafana-agent-1 (external exporter)
```
server:
  log_level: info

metrics:
  global:
    scrape_interval: 15s
    external_labels:
      node_name: grafana-agent

    remote_write:
      - url: https://192.168.100.152:8095/api/v1/push
        tls_config:
          insecure_skip_verify: true
        headers:
          X-Scope-OrgID: test
        basic_auth:
          username: test
          password: test


  wal_directory: "/var/lib/grafana-agent"
  wal_cleanup_age: "12h"
  configs:
    - name: agent
      host_filter: false
      scrape_configs:
        - job_name: "node-exporter"
          # scrape_interval: 1m
          static_configs:
            - targets: ["node-exporter:9100"]
        - job_name: "cadvisor"
          # scrape_interval: 1m
          static_configs:
            - targets: ["cadvisor:8080"]

# https://grafana.com/docs/agent/latest/configuration/integrations/
integrations:
  agent:
    enabled: false
  node_exporter:
    enabled: false
```

### Steps to reproduce

use docker test 

### Software version

agent version v0.35.4
