### ISSUE TITLE
Alloy conversion of otelcol `filelog` lacks `operators`

### ISSUE THREAD

**Issue by cyrille-leclerc** [grafana/alloy#3768]
### What's wrong?

`alloy convert --source-format=otelcol ` doesn't convert the `filelog/operators` entries

### Example OTel Collector config including `filelog/operators`

<details>
<summary>Example OTel Collector config including `filelog/operators` </summary>

```yaml
receivers:
  filelog/zap-logs:
    # ZAP default config: https://github.com/uber-go/zap/blob/v1.27.0/config.go#L124
    #
    # Example Go Zap log line in K8s pod logs
    # 2025-06-02T16:36:32.243Z stderr F {
    #  "level":"info",
    #  "ts":1748882192.242885,
    #  "caller":"recommender/recommender.go:176",
    #  "msg":"Generating recommendations..."}
    include:
      - /var/log/pods/*/*/*.log
    exclude:
      # Exclude logs from all containers named otel-collector
      - /var/log/pods/*/otel-collector/*.log
    start_at: beginning # DEV ENVIRONMENT: Start reading from the beginning of the log files
    include_file_path: true
    include_file_name: false
    operators:

      - type: container
        id: container-parser

      - type: json_parser
        keep_field: false # Remove the original 'body' field after parsing
        timestamp:
          parse_from: attributes.ts
          layout: 's.ns'
          layout_type: 'epoch'
        severity:
          parse_from: attributes.level

      - id: remove_ts
        type: remove
        field: attributes.ts
        
      - id: remove_level
        type: remove
        field: attributes.level

      - id: caller_parser
        type: regex_parser
        parse_from: attributes.caller
        regex: '^(?P<code_file_path>[^:]+):(?P<code_line_number>\d+)$' # Regex to match file and line number
      - id: rename_code_file_path
        type: move # Rename 'code_file_path' to 'code.file.path'
        from: attributes.code_file_path
        to: attributes["code.file.path"]
      - id: rename_code_line_number
        type: move # Rename 'code_line_number' to 'code.line.number'
        from: attributes.code_line_number
        to: attributes["code.line.number"]
      - id: remove_caller
        type: remove # Remove the original 'caller' field
        field: attributes.caller

      - id: move_msg_to_body
        type: move # Move the 'msg' field to the log body
        from: attributes.msg
        to: body
        if: 'attributes.msg != nil' # Only move if 'msg' exists
  
      - id: move_error_to_exception_message
        type: move # Move the 'error' field to 'exception.message'
        from: attributes.error
        to: attributes["exception.message"]
        if: 'attributes.error != nil' # Only move if 'error' exists

      - id: move_stacktrace_to_exception_stacktrace
        type: move # Move the 'stacktrace' field to 'exception.stacktrace'
        from: attributes.stacktrace
        to: attributes["exception.stacktrace"]
        if: 'attributes.stacktrace != nil'

      # IS IT A GOOD IDEA TO NORMALIZE CUSTOM FIELDS
      # IN THE INGESTION PIPELINE RATHER THAN DOING IT IN 
      # THE CODE USING THE OTEL CONSTANTS? 
      # LONG TERM IS BETTER TO DO IT IN THE CODE.
      # ON THE OTHER HAND, RENAMING ZAP LOG FIELDS TO OTEL
      # IN THE PIPELINE IS A GOOD SOLUTION
      - id: rename_status
        type: move
        from: attributes.status
        to: attributes["http.response.status.code"]
        if: 'attributes.status != nil'
      - id: rename_user_agent
        type: move
        from: attributes["user-agent"]
        to: attributes["http.request.user_agent"]
        if: 'attributes["user-agent"] != nil'
      - id: move_method
        type: move
        from: attributes.method
        to: attributes["http.request.method"]
        if: 'attributes.method != nil' # Only move if 'method' exists
      - id: move_path
        type: move
        from: attributes.path
        to: attributes["url.path"]
        if: 'attributes.path != nil' # Only move if 'path' exists
      - id: move_query
        type: move
        from: attributes.query
        to: attributes["url.query"]
        if: 'attributes.query != nil' # Only move if 'query' exists
      - id: move_ip
        type: move
        from: attributes.ip
        to: attributes["client.address"]
        if: 'attributes.ip != nil' # Only move if 'ip' exists

processors:
  transform/parse_zap_logs:
    log_statements:
      - context: log
        statements:
          # instrumentation_scope.name = firstNonNull(attributes["logger"], attributes["code.file.path"])
          # implement logic in a transform processor because doing it in a filelog receiver operator causs
          # "panic: runtime error: invalid memory address or nil pointer dereference"
          # opentelemetry-collector-contrib/pkg/stanza@v0.126.0/operator/transformer/copy/transformer.go:32
          - set(instrumentation_scope.name, attributes["logger"]) where attributes["logger"] != nil
          - set(instrumentation_scope.name, attributes["code.file.path"]) where attributes["logger"] == nil and attributes["code.file.path"] != nil
          - delete_key(attributes, "logger")

  transform/set_global_attributes:
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["deployment.environment.name"], "production") where resource.attributes["deployment.environment.name"] == nil
          - set(resource.attributes["k8s.cluster.name"], "dev-us-east-0") where resource.attributes["k8s.cluster.name"] == nil

  transform/emulate_k8s_attributes_processor:
    # DEV ENVIRONMENT: Emulate Kubernetes attributes extraction
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["service.name"], "policy-api") where resource.attributes["service.name"] == nil
          - set(resource.attributes["service.namespace"], "adaptive-traces") where resource.attributes["service.namespace"] == nil
exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [filelog/zap-logs]
      processors: [transform/parse_zap_logs, transform/emulate_k8s_attributes_processor, transform/set_global_attributes]
      exporters: [debug]
  telemetry:
    metrics:
      level: none
```

</details>

### Output lacking `operators`

```
alloy convert --source-format=otelcol /opt/otelcol/etc/otelcol-adaptive-traces.yml
otelcol.receiver.filelog "default_zap_logs" {
	include = ["/var/log/pods/*/*/*.log"]
	exclude = ["/var/log/pods/*/otel-collector/*.log"]

	ordering_criteria { }
	start_at         = "beginning"
	fingerprint_size = "1000B"

	multiline { }
	include_file_name = false
	include_file_path = true
}

otelcol.processor.transform "default_parse_zap_logs" {
	log_statements {
		context    = "log"
		statements = ["set(instrumentation_scope.name, attributes[\"logger\"]) where attributes[\"logger\"] != nil", "set(instrumentation_scope.name, attributes[\"code.file.path\"]) where attributes[\"logger\"] == nil and attributes[\"code.file.path\"] != nil", "delete_key(attributes, \"logger\")"]
	}

	output {
		logs = [otelcol.processor.transform.default_emulate_k8s_attributes_processor.input]
	}
}

otelcol.processor.transform "default_emulate_k8s_attributes_processor" {
	log_statements {
		context    = "log"
		statements = ["set(resource.attributes[\"service.name\"], \"policy-api\") where resource.attributes[\"service.name\"] == nil", "set(resource.attributes[\"service.namespace\"], \"adaptive-traces\") where resource.attributes[\"service.namespace\"] == nil"]
	}

	output {
		logs = [otelcol.processor.transform.default_set_global_attributes.input]
	}
}

otelcol.processor.transform "default_set_global_attributes" {
	log_statements {
		context    = "log"
		statements = ["set(resource.attributes[\"deployment.environment.name\"], \"production\") where resource.attributes[\"deployment.environment.name\"] == nil", "set(resource.attributes[\"k8s.cluster.name\"], \"dev-us-east-0\") where resource.attributes[\"k8s.cluster.name\"] == nil"]
	}

	output {
		logs = [otelcol.exporter.debug.default.input]
	}
}

otelcol.exporter.debug "default" {
	verbosity = "Detailed"
}
```

### Steps to reproduce

* Create an otelcol config using the example above
* run ``alloy convert --source-format=otelcol path/to/otelcol-config.yaml`
* Checkout the output

### Software version

v1.8.3

### Configuration

```text

```

### Logs

```text

```
