### ISSUE TITLE
Docs feedback: Alloy 1.9.1 - prometheus.exporter.windows - documentation incomplete / wrong

### ISSUE THREAD

**Issue by Nachtfalkeaw** [grafana/alloy#3812]
### URL

https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.exporter.windows/

### Feedback

list of collectors is not reflecting windows_exporter collectors.

"gpu" collector is missing in alloy
"logon" collector is listed in alloy but deprectaed in windows_expiorter
"cs" collector is deprectaed but not marked as deprecated on alloy

"performancecounter" collector is missing an example of 1-2 performancecounter metrics in the external yml file to understand formatting.

**Comment by Nachtfalkeaw** [comment]
My performance counter example looks like this:

```
collector:
  performancecounter:
    objects: |-
        - name: "pf1"
          object: "Memory"
          instance_label: "Arbeitsspeicher"
          counters:
              - name: "Cache Faults/sec"
                type: "counter"
                labels:
                  label_name: "label_value"
```

But I tried with this, too from windows exporter github example.
https://github.com/prometheus-community/windows_exporter/blob/v0.30.7/docs/collector.performancecounter.md#example
```
collector:
  performancecounter:
    objects: |-
      - name: memory
        object: "Memory"
        counters:
          - name: "Cache Faults/sec"
            type: "counter" # optional
```


My prometheus.exporter.windows yml looks like this:
```
prometheus.scrape "windows_exporter" {
  job_name = "windows_exporter"
  scrape_interval = "15s"
  scrape_timeout = "14s"
  extra_metrics = true

  targets = prometheus.exporter.windows.windows_exporter.targets

  forward_to = [prometheus.relabel.windows_exporter.receiver]

}

prometheus.exporter.windows "windows_exporter" {

  enabled_collectors = ["cache","cpu","cpu_info","diskdrive","license","logical_disk","memory","net","os","pagefile","physical_disk","process","remote_fx","smb","smbclient","system","tcp","terminal_services","time","udp","update","vmware","filetime","performancecounter"]

  // deprecated:       ,"cs"
  // crash:            ,"dns","gpu",]
  // not used by us:   ,"dfsr","fsrmquota","hyperv","iis","mscluster","msmq","mssql","netframework","service","textfile","thermalzone","smtp","ad","adcs","adfs","container","dhcp","exchange","printer","scheduled_task"


  process {
    include = ".+"
    exclude = "Idle"   // kann man sich auch ausrechen.
  }

//  dns {
//    enabled_list = ["wmi_stats"]
//  }

  smb {
    enabled_list = ["ServerShares"]
  }

  smb_client {
    enabled_list = ["ClientShares"]
  }

  performancecounter {
    objects = local.file.collect_windows_performancecounter.content
  }
}


local.file "collect_windows_performancecounter" {
  filename = "./config_bbk/collect_windows_performancecounter.yml"
}

prometheus.relabel "windows_exporter" {

  // relabel Funktion um dem Job den richtigen namen zu geben
  rule {
    action        = "replace"
    replacement   = "windows_exporter"
    target_label  = "job"
  }

  forward_to = [prometheus.relabel.localhost.receiver]
}
```

Error:
```
Error: C:\Program Files\GrafanaLabs\Alloy\config_bbk\collect_windows_metrics.alloy:23:1: Failed to build component: building component: yaml: unmarshal errors:
  line 1: cannot unmarshal !!map into []performancecounter.Object
```

**Comment by Nachtfalkeaw** [comment]
This notice is not relevant anymore. The windows_exporter was rebuild and does not crash if collectors can not be used but only prints logs. It was aligned with node_exporter behaviour:

```
Caution

Certain collectors cause Alloy to crash if those collectors are used and the required infrastructure isn’t installed. These include but aren’t limited to mscluster, vmware, nps, dns, msmq, ad, hyperv, and scheduled_task.

The cs collector has been deprecated and may be removed in future versions of the exporter.
```

https://github.com/prometheus-community/windows_exporter/pull/1769
https://github.com/prometheus-community/windows_exporter/issues/1748

**Comment by dehaansa** [comment]
Thanks for these notes! Most of these changes are being fixed for next release already in [this](https://github.com/grafana/alloy/pull/4037) PR, but we don't have a documentation example for the performance counters. I'll take a look at revisiting the docs before merging that PR if possible. CC @clayton-cornell for docs note.

**Comment by clayton-cornell** [comment]
I've added this issue to the Alloy docs tracking so it's not missed/lost in the shuffle.

**Comment by dehaansa** [comment]
I went and tested on a windows machine and tested the sample config from upstream and had success. I'll look to update the docs outside of that earlier linked PR as this would be relevant to last release as well, but as long as your `yaml` file is an array of objects matching the performance counter expectations it should work.

I've made a PR to update the docs with a minimal [example](https://github.com/grafana/alloy/pull/4077), feel free to offer a more complex example for the docs if you're interested. I lack capacity right now to test a more complex example that pulls more performance counters.

```
local.file "pc" {
  filename = "C:/.../pc.yaml"
}

prometheus.exporter.windows "vmStats" {
  enabled_collectors = ["performancecounter"]
  

  performancecounter {
    objects = local.file.pc.content
  }
}
```

and the following in pc.yaml
```
- name: memory
  object: "Memory"
  counters:
    - name: "Cache Faults/sec"
      type: "counter" # optional
```
