### ISSUE TITLE
Alloy suddenly starts to set all lines at the same timestamp for a specific logfile

### ISSUE THREAD

**Issue by zeylos** [grafana/alloy#3831]
### What's wrong?

Hello,

I'm scrapping logs with the following config : 
```
loki.source.file "portailback" {
  targets = [
    {__path__ = "/path/to/nhub-back.log", service_name = "portailback"},
  ]
  forward_to = [loki.process.portailback.receiver]
}

loki.process "portailback" {
  forward_to = [loki.process.default.receiver]

  stage.regex {
      expression = `^(?s)(?P<time>\S+ \S+),\d{3} (?P<level>\S+) .*$`
  }

  stage.timestamp {
    source = "time"
    format = "2006-01-02 03:04:05"
  }
}

loki.process "default" {
  forward_to = [loki.write.default.receiver]

  // Drop logs >24h ago
  stage.drop {
      older_than          = "24h"
      drop_counter_reason = "too old"
  }

  // Add the 'instance' label to every log
  // Add the 'env' label to every log
  stage.static_labels {
    values = {
      "instance"  = "xx.lan",
      "env" = "prod",
    }
  }
}

// Write logs to loki
loki.write "default" {
  endpoint {
    url = "http://loki1.lan:3100/loki/api/v1/push"
  }
}
```

Everything works fine until at some point alloy decides to set all the logs to the same timestamp until i restart it : 

![Image](https://github.com/user-attachments/assets/55c85018-d968-4706-be38-b3c650519efb)

As you can see below the timestamps in the logs are still alright but alloy sets everything at 12:59 UTC : 

![Image](https://github.com/user-attachments/assets/f787b928-8b94-4156-922a-2e1022a70e4a)

I only have two log lines at this timestamp for the alloy daemon, which does not seem to correlate with loki scrapping. Also this log appears on only one of the 5 machines where this happens : 
```
Jun 12 15:00:50 portailback2 alloy[4060746]: ts=2025-06-12T13:00:50.49066003Z level=info msg="Retrying after duration specified by Retry-After header" component_path=/ component_id=prometheus.remote_write.default subcomponent=rw remote_na>
Jun 12 15:00:58 portailback2 alloy[4060746]: ts=2025-06-12T13:00:58.491003713Z level=warn msg="Failed to send batch, retrying" component_path=/ component_id=prometheus.remote_write.default subcomponent=rw remote_name=8f33ba url=http://mim>
```

Now the fun part : 
* this happens only on one type of machine (portailback) and only on the logfile mentionned
* this happens every day at 12:59 UTC

I have no cron or scheduled job running at this specific timestamp and the logfile is rotated at midnight without any issue.

I don't really have any idea what to look for, I use the same type of config on a lot of logfiles and everything works fine. Could someone give me ideas on what could be happening ?

Thanks !

### Steps to reproduce

Alloy config : 
```
loki.source.file "portailback" {
  targets = [
    {__path__ = "/path/to/nhub-back.log", service_name = "portailback"},
  ]
  forward_to = [loki.process.portailback.receiver]
}

loki.process "portailback" {
  forward_to = [loki.process.default.receiver]

  stage.regex {
      expression = `^(?s)(?P<time>\S+ \S+),\d{3} (?P<level>\S+) .*$`
  }

  stage.timestamp {
    source = "time"
    format = "2006-01-02 03:04:05"
  }
}

loki.process "default" {
  forward_to = [loki.write.default.receiver]

  // Drop logs >24h ago
  stage.drop {
      older_than          = "24h"
      drop_counter_reason = "too old"
  }

  // Add the 'instance' label to every log
  // Add the 'env' label to every log
  stage.static_labels {
    values = {
      "instance"  = "xx.lan",
      "env" = "prod",
    }
  }
}

// Write logs to loki
loki.write "default" {
  endpoint {
    url = "http://loki1.lan:3100/loki/api/v1/push"
  }
}
```

Log lines : 
```
2025-06-12 13:56:30,588 INFO foo
2025-06-12 13:56:43,328 INFO bla
2025-06-12 13:56:43,460 INFO bar
```

Loki config : 
```
# Monolithic mode
target: all

# Disable auth and tenants
auth_enabled: false

# Disable clustering
common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1

# Configure log indexes
schema_config:
  configs:
  - from: 2025-06-01
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: ./index
    cache_location: ./index_cache
    cache_ttl: 24h
  use_thanos_objstore: true
  object_store:
    s3:
      bucket_name: ${LOKI_S3_BUCKET}
      endpoint: ${LOKI_S3_ENDPOINT}
      access_key_id: ${LOKI_S3_ACCESSKEY}
      secret_access_key: ${LOKI_S3_SECRETKEY}

ingester:
  wal:
    dir: ./wal

chunk_store_config:
  chunk_cache_config:
    memcached_client:
      addresses: 127.0.0.1:11211
query_range:
  cache_results: true
  results_cache:
    cache:
      memcached_client:
        addresses: 127.0.0.1:11211

# Configure compactor for retention
compactor:
  retention_enabled: true
  delete_request_store: s3
  working_directory: ./compactor

limits_config:
  retention_period: 744h

server:
  log_level: warn
```

### System information

Linux 5.15.0-89-generic - Ubuntu 22.04

### Software version

alloy, version v1.9.1 (branch: HEAD, revision: d3d7931)

### Configuration

```text

```

### Logs

```text

```
