### ISSUE TITLE
prometheus.operator.scrapeconfigs ignores file and http SD configs

### ISSUE THREAD

**Issue by rickard-von-essen** [grafana/alloy#3840]
### What's wrong?

The CRD [monitoring.coreos.com/v1alpha1: ScrapeConfig](https://doc.crds.dev/github.com/prometheus-operator/prometheus-operator/monitoring.coreos.com/ScrapeConfig/v1alpha1@v0.65.1) contains the following objects:

- `fileSDConfigs`
- `honorLabels` ✔ 
- `honorTimestamps` ✔ 
- `httpSDConfigs`
- `metricsPath` ✔ 
- `relabelings` ✔ 
- `staticConfigs` ✔ 

But the code in [config_gen_scrapeconfig.go](https://github.com/grafana/alloy/blob/main/internal/component/prometheus/operator/configgen/config_gen_scrapeconfig.go) doesn't parse `fileSDConfigs` nor `httpSDConfigs`. This limitation isn't mentioned in the [docs](https://grafana.com/docs/alloy/latest/reference/components/prometheus/prometheus.operator.scrapeconfigs/).

### Steps to reproduce

Alloy config:

```
prometheus.operator.scrapeconfigs "sc" {
    forward_to = <RECEIVER_LIST>
}
```

Load ScrapeConfig into k8s:
```
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: bug
  namespace: alloy
spec:
  jobName: fails-sd
  httpSDConfigs:
  - url: http://remotehttp.alloy.svc.cluster.local/sd.json
  metricsPath: /scrape
```

### Software version

5126d5ff9e3420ea81cbbeb0ac856623a7abab2d

### Configuration

```text

```

### Logs

```text

```
