### ISSUE TITLE
Feature Request: Configure custom metrics with prometheus.exporter.oracledb component

### ISSUE THREAD

**Issue by wwalters12** [grafana/alloy#419]
### Request

The exporter that the [prometheus.exporter.oracledb](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.exporter.oracledb/) component is based on allows you to configure custom metrics: https://github.com/iamseth/oracledb_exporter/tree/master#custom-metrics

We would like to be able to also configure custom metrics with the `prometheus.exporter.oracledb` component.

### Use case

Creating custom metrics based on SQL queries would greatly increase the utility of the component. We currently run custom SQL queries through a Splunk plugin to create custom metrics from our Oracle databases. We would like to produce the custom metrics from the Grafana agent instead so that we can utilize the grafana ecosystem to better setup observability on our Oracle databases.

**Comment by StefanKurek** [comment]
Is this issue actually `Open` ATM?

**Comment by peter-grafana** [comment]
👋 @schmikei I was taking a look at this as a professional services customer was asking about this functionality. I wanted to highlight this as you mentioned the potential security risk.

I spotted [this line](https://github.com/grafana/alloy/blob/f60d9666f2a2dfc2039620cfd2939467ae2cfaa0/CHANGELOG.md?plain=1#L339) tucked away in the changelog for v1.3.0 which in turn led me to [this](https://github.com/grafana/alloy/blob/f60d9666f2a2dfc2039620cfd2939467ae2cfaa0/internal/component/prometheus/exporter/oracledb/oracledb.go#L50) in `/internal/component/prometheus/exporter/oracledb/oracledb.go` and the [corresponding test](https://github.com/grafana/alloy/blob/f60d9666f2a2dfc2039620cfd2939467ae2cfaa0/internal/component/prometheus/exporter/oracledb/oracledb_test.go#L31). 
It appears the functionality has been added, but not documented! 

To be clear I've not tested if this actually works or not.

**Comment by dehaansa** [comment]
CC @clayton-cornell this appears to be present in the code, but missing in documentation.

**Comment by 6fears7** [comment]
I tested this extensively today. 


The current issue is that the oracledb_exporter is expecting the data being passed to the custom_metrics field to be a filename, not YAML content. 

Alloy config:
```

remote.kubernetes.configmap "mydatabase" {
	namespace = "prometheus"
	name      = "oracle-config"
}
prometheus.exporter.oracledb "mydatabase" {
    connection_string = "someConnectionString"
	custom_metrics =  remote.kubernetes.configmap.mydatabase.data["custom-metrics-mydatabase.yaml"]
}
```
Example ConfigMap
```yaml
apiVersion: v1
data:
  custom-metrics-mydatabase.yaml: |
    metrics:
      - context: "slow_queries"
        metricsdesc:
          p95_time_usecs: "Gauge metric with percentile 95 of elapsed time."
          p99_time_usecs: "Gauge metric with percentile 99 of elapsed time."
        request:
          "select percentile_disc(0.95) within group (order by elapsed_time) as p95_time_usecs,
          percentile_disc(0.99) within group (order by elapsed_time) as p99_time_usecs
          from v$sql where last_active_time >= sysdate - 5/(24*60)"

kind: ConfigMap
metadata:
  name: oracle-config
  namespace: mydatabase
```
I verified this by using the metric example they use as valid YAML in the [oracledb_test.go file](https://github.com/grafana/alloy/blob/main/internal/component/prometheus/exporter/oracledb/oracledb_test.go#L93) and the error in the log was: 

```
"Unable to get file hash" │
│ ="open metrics:\n  - context: \"slow_queries\"\n    metricsdesc:\n       │
│ p95_time_usecs: \"Gauge metric with percentile 95 of elapsed time.\"\n   │
│     p99_time_usecs: \"Gauge metric with percentile 99 of elapsed time.\" │
│ \n    request:\n      \"select percentile_disc(0.95) within group (order │
│  by elapsed_time) as p95_time_usecs: 
file name too long"  
```

which is referring to this line in the base [oracledb exporter](https://github.com/iamseth/oracledb_exporter/blob/8dab2f552a8640b4f187986fe9e6ced7b7064258/collector/collector.go#L364)
