### ISSUE TITLE
Need help scraping custom /metrics endpoint in Kubernetes

### ISSUE THREAD

**Issue by ATroschke** [grafana/alloy#448]
Hello!

I am pretty new to the prometheus/grafana world, but am interested in learning it since I am developing microservices and now facethe issue of observability.

I have installed the Grafana Agent following the "Connect Data > Kubernetes" flow and am sending node-exporter metrics to Grafana Cloud. Now I want to set it up to monitor my services which have an http endpoint on (pod-name:8080/metrics) and a service (pod-metrics/metrics). I've been sitting at the README's of Grafana Agent and Grafana Agent Operator for almost a whole day and never got this to work, not even with the most basic Job definition.

Here is that "very basic" Job definition
```
        - job_name: pod-metrics
          honor_labels: true
          metrics_path: /metrics
          scheme: http
          static_configs:
            - targets: ['pod-metrics']
 ```

The Service is a ClusterIP service and is accessible in the cluster, which I've confirmed via a basic curl.
The Pod sits in a different namespace than Grafana (to be exact in the 'default' namespace while the operator is in the 'grafana' namespace)
