### ISSUE TITLE
Tracing: Prom SD resolves wrong target/container from Pod

### ISSUE THREAD

**Issue by grelland** [grafana/alloy#450]
Hello!

I'm running Agent in k8s for forwarding traces to Tempo. 

I've instrumented a test application which sends OTLP traces to Agent. The application is a Pod with **two containers**: an app container and a sidecar (SQL proxy).

The relevant part of the agent config looks like this:
```yaml
traces:
     # snip
      scrape_configs:
        - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: node
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: false
```

Now - the traces are flowing just fine through this and ends up in Tempo as expected.

The issue I'm facing, however, is that the spans end up with the `container` resource attribute from the aforementioned _sidecar_ container, and not the _app_ container - which actually emits the trace.

Note: 
- The sidecar is not a scrape target for prometheus at all.
- Debug logs from the agent shows both containers being discovered as targets

I've tried my best to understand if this is a configuration issue, bug or instrumentation issue, but am not getting much wiser. 
If my understanding is correct the trace processing in Agent uses promsd to resolve the k8s labels for a Pod, but I cannot identify the logic (if any) for handling of multiple targets given a Pod, and how that might map to the source of a trace.

Thanks!
