### ISSUE TITLE
Proposal: Flow modules as Kubernetes custom resources

### ISSUE THREAD

**Issue by rfratto** [grafana/alloy#457]
_(Originally posted in https://github.com/grafana/agent/issues/2898#issuecomment-1414827146)_

The introduction of modules opens the door for users who want to split configuration by team; where each team has their own module where common settings can be passed through it via arguments or exported via exports.

However, this is currently difficult to take advantage of on Kubernetes, where you must store modules in mounted files or expose them via some network mechanism (such as `remote.s3` or `remote.http`). 

I propose a new CRD called `AgentModule` which defines a Flow module to be loaded. Then, I propose to introduce a `module.kubernetes` component to discover and load those AgentModule custom resources.   

## Goals 

1. Make it easy to modularize configs in Kubernetes environments 

## Non-goals 

1. Allow Kubernetes-based modules to accept non-string arguments 
2. Allow Kubernetes-based modules to export values

### AgentModule CRD

The `AgentModule` CRD primarily encapsulates a River configuration file. The name `AgentModule` is used instead of `FlowModule` as "Grafana Agent Flow" is a temporary term introduced to distinguish itself from static mode.

There are three primary ways of specifying the module source:

1. Inline source:

   ```yaml 
   apiVersion: monitoring.grafana.com/v1alpha1
   kind: AgentModule
   metadata:
     ...
   spec:
     # Provide the module source that will be loaded.
     source: |
       RIVER_CONFIG
   ```

3. Source from ConfigMap in the same namespace:

   ```yaml
   apiVersion: monitoring.grafana.com/v1alpha1
   kind: AgentModule
   metadata:
     ...
   spec:
     # Load the module source from a ConfigMap. 
     sourceFrom:
       configMapKeyRef:
         name: CONFIGMAP_NAME
         key: CONFIGMAP_KEY
   ```

4. Source from Secret in the same namespace: 

   ```yaml 
   apiVersion: monitoring.grafana.com/v1alpha1
   kind: AgentModule
   metadata:
     ...
   spec:
     # Load the module source from a Secret. 
     sourceFrom:
       secretKeyRef:
         name: SECRET_NAME 
         key: SECRET_KEY 
   ```

The following keys are mutually exclusive in the CRD and exactly one must be provided:

* `spec.source`
* `spec.sourceFrom.configMapKeyRef` 
* `spec.sourceFrom.secretKeyRef`

### module.kubernetes component

The `module.kubernetes` component is responsible for discovering AgentModule resources, interpreting their configs, and building and running the appropriate Flow modules. 

`module.kubernetes` accepts a configuration very similar to [loki.source.podlogs](https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.podlogs) in terms of connecting and discovering AgentModules resources: 

```river 
// Find all AgentModules labeled agent=primary and run them. 
module.kubernetes "default" {
  // Selector for AgentModule resources:
  selector {
    match_labels = { agent = "primary" }
  }
}
```

`module.kubernetes` has the following restrictions: 

1. `module.kubernetes` **can not** pass arguments to modules directly, as it may load a dynamic number of modules with different sets of arguments. 
  * See the section below for how this will be partially handled. 
3. Exports of modules loaded by `module.kubernetes` are ignored. 

### Passing arguments to AgentModule resources 

Because `module.kubernetes` cannot pass arguments to modules directly, the AgentModule CRD itself is responsible for defining how arguments get resolved into values: 

```yaml 
apiVersion: monitoring.grafana.com/v1alpha1
kind: AgentModule
metadata:
  ...
spec:
  # `spec.source` is used here to show the config, but this 
  # could also be `spec.sourceFrom`. 
  source: | 
    argument "ARGUMENT_A" { } 
    argument "ARGUMENT_B" { } 
    argument "ARGUMENT_C" { }
  arguments:
    # Provide argument value From a constant string: 
    - name: ARGUMENT_A 
      value: "ARGUMENT_VALUE"
    # Provide argument value from a ConfigMap: 
    - name: ARGUMENT_B  
      valueFrom:
        configMapKeyRef:
          name: CONFIGMAP_NAME
          key: CONFIGMAP_KEY
    # Provide argument value from a Secret:
    - name: ARGUMENT_C 
      valueFrom:
        secretKeyRef:
          name: SECRET_NAME
          key: SECRET_KEY
```

When loading modules, `module.kubernetes` will resolve the `spec.arguments` field and use it to pass values to the loaded module. 

This allows for passing basic arguments (like secrets) to modules, but does not allow for passing River capsule values; this means that the initial implementation of this functionality assumes that the AgentModule resources are isolated in the pipeline. 

If the module has arguments, all required arguments must be provided in `spec.arguments`. A AgentModule resource will be rejected if `spec.arguments` defines arguments not specified in the module source. 

### Why support arguments in AgentModule at all? 

An obvious question is why should AgentModule support `spec.arguments` at all, rather than the module writer inlining everything they can? 

While it would be possible to use grafana/agent#2976 to achieve the same behavior, `spec.arguments` is intended to be useful for security hardening. If Grafana Agent is running in an environment where AgentModules should not be allowed to have the same access to the Kubernetes API as the running Flow process is (#3439), an alternative mechanism is required to allow AgentModules to be able to expose secrets to AgentModules without hard-coding them directly into the config. 

## Resources 

<details>
<summary>Full reference of AgentModule CRD</summary>

```yaml 
apiVersion: monitoring.grafana.com/v1alpha1
kind: AgentModule
metadata: KUBERNETES_METADATA
spec:
  # Define an inline River config. 
  # source is mutually exclusive with sourceFrom. 
  source: INLINE_SOURCE
  sourceFrom:
    # Retrieve a River config from a ConfigMap. 
    # configMapKeyRef is mutually exclusive with secretKeyRef. 
    configMapKeyRef:
      name: CONFIGMAP_NAME
      key: CONFIGMAP_KEY
    # Retrieve a River config from a Secret. 
    # configMapKeyRef is mutually exclusive with configMapKeyRef. 
    secretKeyRef:
      name: SECRET_NAME 
      key: SECRET_KEY  
  arguments:
    # Provide value for an argument in the module source.  
    - name: ARGUMENT_NAME 
      # Static value. Mutually exclusive with valueFrom.
      value: "ARGUMENT_VALUE"
      valueFrom:
        # Argument value from a ConfigMap. Mutually exclusive 
        # with secretKeyRef.
        configMapKeyRef:
          name: CONFIGMAP_NAME
          key: CONFIGMAP_KEY
        # Argument value from a Secret. Mutually exclusive with 
        # configMapKeyRef.
        secretKeyRef:
          name: SECRET_NAME
          key: SECRET_KEY
    - ... 
```

</details>
