### ISSUE TITLE
"htInstanceUrl" in grafana cloud stack api response doesn't contain required port for tempo remote write

### ISSUE THREAD

**Issue by zlepper** [grafana/alloy#469]
Let me prefix by saying this: I don't know if this should be considered a bug in grafana cloud or the tempo remote-write

If you look at the api response for list-stacks in the grafana cloud api: https://grafana.com/docs/grafana-cloud/api-reference/cloud-api/#list-stacks, you can see it contains
```
 "htInstanceUrl": "https://tempo-us-central1.grafana.net",
```
If you just pass this directly to the grafana agent remote_write.endpoint:

```yaml
traces:
  configs:
    - name: integrations
      remote_write:
        - endpoint: ${TRACING_URL}
```
then the remote write will not work because a port has not been configured, even though it should be quite easy to infer from the `https` protocol. 

Working around this is trivial on my side since i can just add `:443`, however, i thought you might want to know :)

Have a nice day :)
