### ISSUE TITLE
Please clarify the 'Analyze and reduce metrics usage with Grafana Mimirtool' docs

### ISSUE THREAD

**Issue by stefanes** [grafana/alloy#484]
I just successfully performed the steps outlined here to limit the number of metrics sent to Prometheus: [Analyze and reduce metrics usage with Grafana Mimirtool](https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/usage-analysis-mimirtool/#analyze-and-reduce-metrics-usage-with-grafana-mimirtool)

However, the part around [adding the `write_relabel_configs`](https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/usage-analysis-mimirtool/#step-3-drop-unused-active-metrics-with-relabel_config) does not cover, at least for the Grafana Agent on Windows with the default config, that the described statement should be added here:
```yaml
integrations:
  prometheus_remote_write:
    ...
```
...and not under:
```yaml
metrics:
  configs:
    - name: integrations
      remote_write:
        ...
```
The documentation just states that:
> A Prometheus or Grafana Agent configuration has a remote_write configuration block similar to that which follows

This maybe perfectly clear for most users, but definitely not for a Grafana Agent/Prometheus n00b like myself... :smile:
