### ISSUE TITLE
Grafana Agent v0.31.0 failing with tail_sampling config

### ISSUE THREAD

**Issue by ErgoPr0xy** [grafana/alloy#494]
Hi, 

I am trying to set up traces again after upgrading to v0.31.0

This is what I am setting (changed for v0.24.0 following the upgrade guide), I also tried removing `- type: probabilistic` as suggested in another issue experiencing a similar problem --> https://github.com/grafana/agent/issues/1837

```
tail_sampling:
  policies:
  - type: probabilistic
    probabilistic:
      sampling_percentage: 15

```
No matter what config I use/change it to - I always get a different error. I've switched to the below for now as a workaround but it is not ideal

```
tail_sampling:
  policies:
  - type: always_sample
```

this works without issue and the agent starts fine

Even if I follow how this is configured from the upstream config I run into the same issue. 

This worked from v0.24.0 to v0.29.0 and I don't see anything related to it in the release notes or upgrade guide. 

Thanks
