### ISSUE TITLE
grafana-agent does not use the DNS TTL for the remote_write endpoint

### ISSUE THREAD

**Issue by oneacl** [grafana/alloy#498]
Hi,

I'm not sure if this issue relates to grafana-agent itself or the remote_write prom library.

I have a (non persistent) load balancer between grafana agent and Mimir.

my relevant agent config is:
```
remote_write:
  - url: https://lb.example.com/api/v1/push
    headers:
      X-Scope-OrgID: example
    queue_config:
      min_backoff: 5s
      max_backoff: 30s
```
I tried setting the scrape_interval to 10s for testing (normally at 60s)

My workflow enforces periodic load balancer recreation (can't do anything about that) and the IP address of lb.example.com will change. The workflow is along these lines: new LB gets created, the DNS for lb.example.com updated to the new one, the old one will be left in place (for a while) for rollback.
However, grafana-agent will keep connecting the old IP indefinitely (the TTL for lb.example.com is 60 seconds).
Even if the load balancer comes back with 503s the agent will continue to try and use it.

Not even HUPing the process helps - after sending SIGHUP I can see in the agent logs that config reload was requested but tcpdump still shows connections to the old IPs.
The source IP on the agent is the same for each connection so that makes me believe that the connection could be persistent (for performance?)

The only way to force the agent to use the new load balancer is to restart the agent completely.

Documentation doesn't seem to indicate any tweak to this behaviour - would it be possible to force a DNS refresh without restarting the agent?

Thank you.
