### ISSUE TITLE
consul_sd_configs __meta_consul_tags relabaling

### ISSUE THREAD

**Issue by suikast42** [grafana/alloy#499]
I am sracping consul metrics over consul_sd_configs
 with the cinfig shown below:

```yaml
       - job_name: "integrations/consul_sd_minio"
          metrics_path: "/minio/v2/metrics/cluster"
          consul_sd_configs:
            - server: "consul.service.consul:8501"
              tags: ["prometheus_minio"]
              tls_config:
                insecure_skip_verify: true
                ca_file: "/certs/ca/ca.crt"
                cert_file: "/certs/consul/consul.pem"
                key_file: "/certs/consul/consul-key.pem"
              datacenter: "{{data_center}}"
              scheme: https
          relabel_configs:
            - source_labels: [__meta_consul_node]
              target_label: instance
            - source_labels: [__meta_consul_service]
              target_label: service
            - source_labels: [__meta_consul_tags]
              separator:     ','
              regex:         '.*,prometheus:server=([^,]+),.*'
              target_label:  'server'
              replacement:   '$${1}'
            - source_labels: [__meta_consul_tags]
              separator:     ','
              regex:         '.*,prometheus:version=([^,]+),.*'
              target_label:  'version'
              replacement:   '$${1}'
```

For mimimize the relabeling config I thought I can relable all consul tags which starts wih prometheus:
with the config:

```yaml
            - source_labels: [__meta_consul_tags]
              separator:     ','
              regex:         'prometheus:([^=]+)=([^,]+)'
              target_label:  '$${1}'
              replacement:   '$${2}'
```

But it seems that grafana agent can relabel on match at time. Right? Or did I miss something?
