### ISSUE TITLE
postgres_exporter integration ignores include/exclude databases config

### ISSUE THREAD

**Issue by snorfalorpagus** [grafana/alloy#501]
I'm trying to use Grafana Agent to export metrics about a single database on a PostgreSQL server. However the `include_databases` option appears to be ignored: all of the databases on the server are reported (e.g. `postgres`, `template0`, ...). Similarly adding these to `exclude_databases` has no effect.

```yaml
integrations:
  postgres_exporter:
    enabled: true
    disable_settings_metrics: true
    data_source_names:
      - postgresql://[redacted]/mydataabse
    autodiscover_databases: true
    include_databases:
      - mydatabase
```

I'm not sure if this is a misconfiguration problem or a bug.

Grafana Agent version information:

```
./agent-linux-amd64 --version
agent, version v0.29.0 (branch: HEAD, revision: 4e92c569)
  build user:       root@ccd16eb532f7
  build date:       2022-11-08T15:16:38Z
  go version:       go1.19.3
  platform:         linux/amd64
```

Running against PostgreSQL 13.7, hosted on AWS RDS.
