### ISSUE TITLE
Listen for AlertManagerConfig CRDs and configure Alertmanager in Grafana Mimir/Cortex

### ISSUE THREAD

**Issue by nicoche** [grafana/alloy#504]
Similarly to https://github.com/grafana/agent/issues/1544, the agent could discover `AlertManagerConfig` CRDs to configure mimir's alert manager via its API

**Comment by jeremych1000** [comment]
Could we help get this over the line please? :) 
So close

**Comment by Daniel-Vaz** [comment]
Plus one for me here also 🤞

**Comment by fculpo** [comment]
+1

How are you managing this right now ?
We are migrating to Alloy with loki and mimir kubernetes rules components to replicate kube-prometheus (prometheus-operator), that is working fine and all is visible in Grafana, but the AM config is lacking (mainly configuring routing to Grafana Oncall integrations depending on labels, etc.)

**Comment by lieberlois** [comment]
+1 

Any updates on this? If you need support with the implementation I'd be happy to help if I find the time - just would need some pointers on how to get started ^^

**Comment by ptodev** [comment]
I had a look at implementing this, but just like #4216 states I personally don't know how to merge the [AlertmanagerConfig CRDs](https://github.com/prometheus-operator/prometheus-operator/blob/3afdfd506b63c71fabdf9dcda7fc81c945208098/pkg/apis/monitoring/v1beta1/alertmanager_config_types.go#L70-L86). For example:

* If two CRDs have receivers with the same name, should they be merged together? Or should we change their names?
* How would we merge `route` and `inhibitRules`? They don't even have name identifiers.
* What if two overlapping CRDs got merged, but then one of them got deleted? We need to prevent the deleted one from deleting things that the non-deleted one still has.

I suppose we'd have to store all active CRDs in memory and the re-merge all of them any time a CRD is added, modified or deleted. That way we can avoid issues with deleted CRDs affecting the config of non-deleted CRDs.

I'm still not sure how the merging should actually be done though. I'm quite new to this topic, so I'd be grateful if anyone with more real world experience would like to shed light on it :)

**Comment by pdf** [comment]
I think the way to go for Alertmanager would be to crib the prometheus-operator config generation code, then load the resulting complete config into mimir as a single op.

**Comment by ptodev** [comment]
Would it be ok if the Alloy component does a few things differently from the operator:
* The global Alertmanager config would come from a string instead of the Alertmanager CRD. That string could be set in Alloy's config directly or it could come from a component like [remote.kubernetes.configmap](https://grafana.com/docs/alloy/latest/reference/components/remote/remote.kubernetes.configmap/). Even if we use a CRD, most of the parameters in it would be unused.
* The `template_files` option in the [Mimir API](https://grafana.com/docs/mimir/latest/references/http-api/#set-alertmanager-configuration) would also be set via a string in the Alloy component's config.

I've been testing a component locally with the following inputs:

<details>
  <summary>Alloy config</summary>

```hcl
remote.kubernetes.configmap "default" {
    namespace = "default"
    name = "alertmgr-global"
}

mimir.alerts.kubernetes "default" {
    address = "http://mimir-nginx.mimir-test.svc:80"
    global_config = remote.kubernetes.configmap.default.data["glbl"]
}
```

</details>

<details>
  <summary>Global Alertmanager config</summary>

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmgr-global
  namespace: default
  labels:
    agent: "yes"
data:
  glbl: |
    global:
      resolve_timeout: 5m
      http_config:
        follow_redirects: true
        enable_http2: true
      smtp_hello: localhost
      smtp_require_tls: true
    route:
      receiver: "null"
    receivers:
    - name: "null"
    - name: "alloy-namespace/global-config/myreceiver"
    templates: []
```

</details>

<details>
  <summary>AlertmanagerConfig CRD 1</summary>

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmgr-config1
  namespace: default
  labels:
    agent: "yes"
spec:
  route:
    receiver: "null"
    routes:
    - receiver: myamc
      continue: true
  receivers:
  - name: "null"
  - name: myamc
    webhookConfigs:
    - url: http://test.url
      httpConfig:
        followRedirects: true
```

</details>

<details>
  <summary>AlertmanagerConfig CRD 2</summary>

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmgr-config2
  namespace: default
  labels:
    agent: "yes"
spec:
  route:
    receiver: "null"
    routes:
    - receiver: 'database-pager'
      group_wait: 10s
      matchers:
      - name: service
        value: webapp
  receivers:
  - name: "null"
  - name: "database-pager"
```

</details>


When I query `curl http://mimir-nginx.mimir-test.svc:80/api/v1/alerts`, I get this output:

<details>
  <summary>Output config</summary>

```yaml
template_files: {}
alertmanager_config: |
    global:
      resolve_timeout: 5m
      http_config:
        follow_redirects: true
        enable_http2: true
      smtp_hello: localhost
      smtp_require_tls: true
    route:
      receiver: "null"
      continue: false
      routes:
      - receiver: default/alertmgr-config1/null
        matchers:
        - namespace="default"
        continue: true
        routes:
        - receiver: default/alertmgr-config1/myamc
          continue: true
      - receiver: default/alertmgr-config2/null
        matchers:
        - namespace="default"
        continue: true
        routes:
        - receiver: default/alertmgr-config2/database-pager
          match:
            service: webapp
          continue: false
    receivers:
    - name: "null"
    - name: alloy-namespace/global-config/myreceiver
    - name: default/alertmgr-config1/null
    - name: default/alertmgr-config1/myamc
      webhook_configs:
      - send_resolved: false
        http_config:
          follow_redirects: true
          enable_http2: true
        url: <secret>
        url_file: ""
        max_alerts: 0
    - name: default/alertmgr-config2/null
    - name: default/alertmgr-config2/database-pager
    templates: []
```

</details>

When I remove the `alertmgr-config1` CRD, the Mimir config becomes:

<details>
  <summary>Output config 2</summary>

```yaml
template_files: {}
alertmanager_config: |
    global:
      resolve_timeout: 5m
      http_config:
        follow_redirects: true
        enable_http2: true
      smtp_hello: localhost
      smtp_require_tls: true
    route:
      receiver: "null"
      continue: false
      routes:
      - receiver: default/alertmgr-config2/null
        matchers:
        - namespace="default"
        continue: true
        routes:
        - receiver: default/alertmgr-config2/database-pager
          match:
            service: webapp
          continue: false
    receivers:
    - name: "null"
    - name: alloy-namespace/global-config/myreceiver
    - name: default/alertmgr-config2/null
    - name: default/alertmgr-config2/database-pager
    templates: []
```

</details>

I need to add a few more tests and I will open a PR to add it in as an experimental component.
