### ISSUE TITLE
traces: Improve Error Message on Tail Sampling policy

### ISSUE THREAD

**Issue by joe-elliott** [grafana/alloy#539]
This policy:

```
        tail_sampling:
          policies:
          - type: and
            and:
              and_sub_policy:
              - type: string_attribute
                string_attribute:
                  key: foo
                  values:
                    - bar
              - type: string_attribute
                string_attribute:
                  key: also_foo
                  values:
                    - also_bar
```

Causes the agent to log [this error](https://github.com/grafana/agent/blob/0b3a1500a1afbf857e6d38fe4a05a5ed52ab6146/pkg/traces/config.go#L528) and exit:
```
msg="error creating the agent server entrypoint" err="failed to create tracing instance default: failed to create pipeline: failed to load otelConfig from agent traces config: malformed sampling policy"
```

Removing the `type: and` key fixes this issue. This config is slightly askew from the [upstream config](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/README.md) which requires `type: and`. 

Can we improve this error message?

Also, this minor difference between configs has caused a fair amount of confusion, can we just accept the `type: and` key to be compatible with upstream?
