### ISSUE TITLE
Failed scrapes prevents series from being deletable

### ISSUE THREAD

**Issue by rfratto** [grafana/alloy#546]
When a scrape fails, series written to the Appender will be discarded with a `Rollback`. This breaks the garbage collection check, where it looks to see if a series is pending a commit. However, the pending commit status is only updated [on Commit, and not on Rollback](https://github.com/grafana/agent/blob/25b8896ddf5d314fbf1d7f04fc48c9d7e39c7dc0/pkg/metrics/wal/wal.go#L698-L705).  

This means the series will never be considered for deletion, and may permanently leak if it never appears in another scrape.

This bug is **not** present in the upstream Prometheus Agent, where a simplification of the GC logic avoided the need for a "pending commit" status. We may not want to bother fixing this downstream and just switch over to Prometheus Agent instead (though that's lightly blocked by grafana/agent#1332).

You can reproduce with the following:

```yaml
server:
  http_listen_port: 12345 

metrics:
  global:
    remote_write:
    - url: CONFIGURE_ME 
  configs:
  - name: default
    scrape_configs:
    - job_name: integrations/agent 
      static_configs:
      - targets: ['127.0.0.1:12345']
        labels:
          __metrics_path__: /integrations/agent/metrics
     sample_limit: 1 

integrations:
  agent:
    enabled: true 
    scrape_integration: false 
```

This causes all scrapes to fail, as the agent target always has more than one sample, and series will never be deleted.
