### ISSUE TITLE
Feature: More granular control over RBAC creation

### ISSUE THREAD

**Issue by petewall** [grafana/alloy#681]
### Request

When deploying via the Helm chart and using `rbac.create = true`, then ClusterRole and ClusterRoleBinding objects are created. Part of those contains this rule:
```yaml
  # needed for remote.kubernetes.*
  - apiGroups: [""]
    resources:
      - "configmaps"
      - "secrets"
    verbs:
      - get
      - list
      - watch
```

This is a very permissive: "Alloy's in yer cluster, readin' yer secrets!"

My feature request: Allow finer grained control over RBAC rules, along the lines of either:

```yaml
rbac:
  create: true
  rules:
...
    - apiGroups: [""]
      resources:
        - "configmaps"
        - "secrets"
      verbs:
        - get
        - list
        - watch
...
```
or provide an option to namespace the rules:
```yaml
rbac:
  create: true
  secrets:
    namespace: []   # Empty namespace means all (e.g. its in the ClusterRole), otherwise, create a Role and RoleBinding for each namespace
```

### Use case

Minimizing the security footprint of Alloy. Allow for reduction or removal of secret access if it's not required.
