### ISSUE TITLE
alloy convert cannot resolve the configuration: scheme "env"

### ISSUE THREAD

**Issue by NissesSenap** [grafana/alloy#874]
### Request

Running alloy convert is unable to handle the `env` syntax of OTEL and provides the following error:

`Error: (Critical) failed to get otelcol config: cannot resolve the configuration: scheme "env" is not supported for uri "env:MY_POD_IP"`

This is how my config looks like.

```
receivers:
  otlp/by-traceid:
    protocols:
      grpc:
        endpoint: ${env:MY_POD_IP}:4316
```

My understanding from the docs is that this is supported by alloy as well: https://grafana.com/docs/alloy/latest/concepts/configuration-syntax/#expressions

### Use case

Make the OTEL convert easier for existing collector users.
