### ISSUE TITLE
`Alloy fmt` use "space" instead of "tab" for indentation

### ISSUE THREAD

**Issue by duthifree** [grafana/alloy#915]
### Request

Is it possible to change indentation from "tab" to "space" when i use `alloy fmt` please ?

### Use case

In Kubernetes, when i create ConfigMap from file,  \n... are prints instead of a newline. It's hard to edit or consult ConfigMap with this formatting.

Today:
```yaml
apiVersion: v1
data:
  test.alloy: "test.example \"xxx\" {\n\foo = \"bar\"\n}\n"
kind: ConfigMap
metadata:
  name: alloy
  namespace: grafana-alloy
```

Expected : 
```yaml
apiVersion: v1
data:
  test.alloy: |
    test.example "xxx" {
      foo = "bar"
    }
kind: ConfigMap
metadata:
  name: alloy
  namespace: grafana-alloy
  ```
