### ISSUE TITLE
Panics when upgrading from v1.0.0 to v1.1.0 on loki.source.docker

### ISSUE THREAD

**Issue by opkaizen** [grafana/alloy#957]
### What's wrong?

When upgrading from v1.0.0 to v1.1.0, the process panics and crashes.
Below configuration is the minimal configuration I got to have Alloy crashing. This is running via docker compose, the compose file is
```
version: '3.7'
services:
  grafana-alloy:
    image: grafana/alloy:v1.1.0
    restart: unless-stopped
    entrypoint:
      - /bin/alloy
      - run
      - --storage.path=/data
      - /etc/alloy/config.alloy

    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro,rslave
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
```

Also I don't understand why Alloy would try to do a Get http:///var/run/docker.sock, is it supposed to be?

### Steps to reproduce

change docker tag from v1.0.0 to v1.1.0

### System information

Linux 5.15.0-87-generic #97-Ubuntu SMP, Docker version 24.0.2 build cb74dfc

### Software version

Grafana Alloy v1.1.0

### Configuration

```text
logging {
	level = "info"
	format = "json"
}

discovery.docker "default" {
	host             = "unix:///var/run/docker.sock"
	refresh_interval = "5s"
}


loki.source.docker "xxx" {
	host             = "unix:///var/run/docker.sock"
	targets          = discovery.docker.default.targets
	forward_to       = []
	refresh_interval = "5s"
}
```

### Logs

```text
{"ts":"2024-05-30T09:15:07.544916166Z","level":"error","msg":"error inspecting Docker container","target":"fa2ddd4bd8f6c8c7c3cc1bfe820f493cb749391e47946d943c05f4e917fb6842","component_path":"/","component_id":"loki.source.docker.xxx","id":"fa2ddd4bd8f6c8c7c3cc1bfe820f493cb749391e47946d943c05f4e917fb6842","error":"Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.43/containers/fa2ddd4bd8f6c8c7c3cc1bfe820f493cb749391e47946d943c05f4e917fb6842/json\": context canceled"}
{"ts":"2024-05-30T09:15:07.546302848Z","level":"warn","msg":"could not transfer logs","component_path":"/","component_id":"loki.source.docker.xxx","target":"docker/fa2ddd4bd8f6c8c7c3cc1bfe820f493cb749391e47946d943c05f4e917fb6842","written":0,"container":"fa2ddd4bd8f6c8c7c3cc1bfe820f493cb749391e47946d943c05f4e917fb6842","err":"context canceled"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3d4cc7e]

goroutine 251 [running]:
github.com/grafana/alloy/internal/component/loki/source/docker/internal/dockertarget.(*Target).Stop(0xc002bc6300)
	/src/alloy/internal/component/loki/source/docker/internal/dockertarget/target.go:238 +0x1e
github.com/grafana/alloy/internal/component/loki/source/docker.(*tailer).Run(0xc003555180, {0x8e87d40, 0xc002c10140})
	/src/alloy/internal/component/loki/source/docker/runner.go:116 +0x2f8
github.com/grafana/alloy/internal/runner.(*Runner[...]).ApplyTasks.func2()
	/src/alloy/internal/runner/runner.go:166 +0x90
created by github.com/grafana/alloy/internal/runner.(*Runner[...]).ApplyTasks in goroutine 174
	/src/alloy/internal/runner/runner.go:163 +0x585
```
